### ISSUE TITLE
It is able to support RNN models like LSTM? (3D array INPUT)

### ISSUE THREAD

**Issue by Alex891** [oegedijk/explainerdashboard#101]
It is possible to adapt this set of dashboards for RNN-based models, such as LSTM networks.

The main problem I am encountering is in the input dataset which, being pre-processed, does not have the traditional linear structure, but is produced by the application of window-based techniques, for example.

The INPUT it's a 3D array

![image](https://user-images.githubusercontent.com/29921525/111197462-c88e9500-85be-11eb-8820-d6742d302801.png)

**Comment by oegedijk** [comment]
Hmm, that's an interesting question! 

It seems that in principle it should be possible: https://www.kaggle.com/phamvanvung/shap-for-lstm

I'm not sure I understand the plots though :)

The whole library is built with tabular applications in mind, so for the most of the functionality you would have to somehow wrangle the shap values into a dataframe format....

**Comment by Alex891** [comment]
Let's say that with the SHAP library I was able to produce the plots I needed.

On the other hand, it seems not possible at the moment to do the same with explainerdashboard, as it seems that it does not provide a DeepExplainer, the one that should be used to work with models like RNN, as they incorporate 3D inputs.

To answer your statement on the dataframe format, yes, I converted and fed data converted into dataframe format to the explainerdashboard function, the error that then produced me is the following:

![image](https://user-images.githubusercontent.com/29921525/111437903-e87ba100-8703-11eb-8621-1bd4d710a01c.png)

as if it only accepted 2D tensors at the moment.

Let's say that with the SHAP library I was able to produce the plots I needed.
On the other hand, it seems not possible at the moment to do the same with explainerdashboard, as it seems that it does not provide a DeepExplainer, the one that should be used to work with models like RNN, as they incorporate 3D inputs.

To answer your statement on the dataframe format, yes, I converted and fed data converted into dataframe format to the explainerdashboard function, the error that then produced me is the following:

as if it only accepted 2D tensors at the moment.

So I was wondering which of the various explainer made available by explainerdashboard should be used for LSTM like models.

![image](https://user-images.githubusercontent.com/29921525/111438137-32648700-8704-11eb-8043-f041e7f1d578.png)

**Comment by oegedijk** [comment]
Hi @Alex891,

In general any model needing shap.DeepExplainer does not seem to be working at the moment, planning on getting that fixed for the next release. Will let you know when I have a fix in the dev branch so that you can test it!

As for the list of explainer, most of them are only there for backward compatibility, so in practice you only need to use `ClassifierExplainer` and `RegressionExplainer`.

**Comment by Alex891** [comment]
Hi @oegedijk 

I had already made a few attempts to get it to work with ClassifierExplainer (or RegressionExplainer), e.g:

**explainer = ClassifierExplainer(model, X_test, y_test, shap="deep", X_background=X_train)**

**(X_test, X_trai:  pandas.Dataframe, y_test: pandas.Series)**

obviously it returned me several type incompatibility errors.

Mainly ClassifierExplainer accepts pandas.DataFrame as input, while internally shap.DeepExplainer works only with numpy.array.


I will be waiting for the next fix!!!

**Comment by oegedijk** [comment]
Hi,

Still haven't really found time to work on the DeepExplainer support, but I think when I get around to it I will limit the scope to tabular DL models. So supporting RNNs will probably remain out of scope for this library. 

Will let you know if anything changes, but closing this for now...
