### ISSUE TITLE
XGBExplainer - can't load dashboard

### ISSUE THREAD

**Issue by mbh86** [oegedijk/explainerdashboard#102]
Hello,

I encountered the following error message when running **ExplainerDashboard with XGBExplainer**:

> \lib\site-packages\explainerdashboard\dashboard_components\composites.py in __init__(self, explainer, title, name, hide_predindexselector, hide_predictionsummary, hide_contributiongraph, hide_pdp, hide_contributiontable, hide_title, hide_selector, **kwargs)
>     279                         hide_selector=hide_selector,  **kwargs)
>     280 
> --> 281         self.index_connector = IndexConnector(self.index, 
>     282                 [self.summary, self.contributions, self.pdp, self.contributions_list])
>     283 
> 
> AttributeError: 'IndividualPredictionsComposite' object has no attribute 'index'

Here is the following code that produce the error:
```
import xgboost as xgb
from explainerdashboard import ExplainerDashboard
from explainerdashboard.explainers import XGBExplainer
from explainerdashboard.datasets import titanic_fare

X_train, y_train, X_test, y_test = titanic_fare()
model = xgb.XGBRegressor(objective='reg:squarederror', n_estimators=5, max_depth=2)
model.fit(X_train, y_train)

explainer = XGBExplainer(model, X_test, y_test)
db = ExplainerDashboard(explainer, shap_interaction=False)
```

Packages versions
- explainerdashboard: 0.2.15 (as well as 0.3.3 which is the latest version)
- xgb: 1.3.3

Thank you for your help.

**edit: issue is also encountered on the latest release version 0.3.3**

**Comment by oegedijk** [comment]
Hi @mbh86,

`XGBExplainer`, is a base class that you should not use directly.  You can simply use the `RegressionExplainer` (and it will convert itself to an` XGBRegressionExplainer` to make xgboost tree prediction available):

```
import xgboost as xgb
from explainerdashboard import ExplainerDashboard
from explainerdashboard.explainers import RegressionExplainer
from explainerdashboard.datasets import titanic_fare

X_train, y_train, X_test, y_test = titanic_fare()
model = xgb.XGBRegressor(objective='reg:squarederror', n_estimators=5, max_depth=2)
model.fit(X_train, y_train)

explainer = RegressionExplainer(model, X_test, y_test)
db = ExplainerDashboard(explainer, shap_interaction=False)
```
