### ISSUE TITLE
Use selected index in ClassifierRandomIndexComponent

### ISSUE THREAD

**Issue by matt-song27** [oegedijk/explainerdashboard#103]
I would like to use selected index in the ClassifierRandomIndexComponent. 
For instance, if an index in the dropdown is selected, is there any way to print out the selected index? I would like to create a customized table after filtering with the selected index value. 

self.index = ClassifierRandomIndexComponent(explainer,
                                                    hide_title=True, 
                                                    hide_index=False,
                                                    hide_slider=True, 
                                                    hide_labels=True,
                                                    hide_pred_or_perc=True,
                                                    hide_selector=True, 
                                                    hide_button=False,
                                                    #index=0
                                                   )
print(self.index.index)

I tried above.
But it printed None in the initial run and not printed anything else after I selected an index.

**Comment by oegedijk** [comment]
Hi @matt-song27,

This is definitely possible, but it will require some knowledge of plotly dash. Here is an example of building custom components for adding a warning for certain indexes (or predictions): https://github.com/oegedijk/explainerdashboard/issues/87

 Have a look and see if that helps you in the right direction..

**Comment by matt-song27** [comment]
@oegedijk 
Thank you for your answer. 
I think I misdirected you. I was able to build custom components using Dash. 
I want to use updated self.index.index after I select it from the dropdown. 

For example, the printed result of below code (print(self.index.index)) was 3658 after initial start.
But then, after I chose a different index, it did not show result of print(self.index.index).  
Could I possibly have any suggestion from you?

class CustomPredictionsTab(ExplainerComponent):
    def __init__(self, explainer, title='', name='None'):
        super().__init__(explainer, title)

        self.index = ClassifierRandomIndexComponent(explainer,
                                                    hide_title=True, 
                                                    hide_index=False,
                                                    hide_slider=True, 
                                                    hide_labels=True,
                                                    hide_pred_or_perc=True,
                                                    hide_selector=True, 
                                                    hide_button=False,
                                                    index=3658,
                                                   )

**print(self.index.index)**

    def layout(self):
        return dbc.Container([
            dbc.Row([dbc.Col([html.H3(' '),self.index.layout()])]),
        ])

**Comment by oegedijk** [comment]
Hi @matt-song27,

That print statement only gets called at the init, so makes sense that you only see it once. So the way to do it is to make a prober index display component, like so:

```
class DisplayIndex(ExplainerComponent):
    def __init__(self, title="Index", name=None, index_selector=None):
        super().__init__(explainer, title, name)
        self.exclude_callbacks(index_selector)

    def layout(self):
        return dbc.Card([
            dbc.CardHeader([
                html.Div([
                    html.H3(self.title, className='card-title'),
                ]), 
            ]),
            dbc.CardBody([
                dbc.Row([
                    dbc.Col([
                        html.Div(id='displayindex-div-'+self.name)
                    ])
                ]),
            ])
        ])

    def component_callbacks(self, app):
        if self.index_selector is not None:
            @app.callback(
                Output('displayindex-div-'+self.name, 'children'),
                [Input(self.index_selector.index_name, 'value')])
            def update_output_div(index):
                return str(index)
            
class CustomPredictionsTab(ExplainerComponent):
    def __init__(self, explainer, title='', name='None'):
        super().__init__(explainer, title)
        self.index_selector = ClassifierRandomIndexComponent(explainer,
                                                hide_title=True, 
                                                hide_index=False,
                                                hide_slider=True, 
                                                hide_labels=True,
                                                hide_pred_or_perc=True,
                                                hide_selector=True, 
                                                hide_button=False,
                                                index=3658,)

        self.index_display = DisplayIndex(index_selector=self.index_selector)

    def layout(self):
            return dbc.Container([
                dbc.Row([
                    dbc.Col([
                        self.index_selector.layout()
                    ])
                ]),
                dbc.Row([
                    dbc.Col([
                        self.index_display.layout()
                    ])
                ]),
            ])
        
ExplainerDashboard(explainer, CustomPredictionsTab).run()
```

All component with an index selector have an `.index_name` property that gives the dash `id` of the index input component. So you can use this in a callback. When passing other components to a constructor of a component, you need to wrap them in an `exclude_callbacks()` as otherwise the callbacks would get registered double, resulting in errors.

**Comment by matt-song27** [comment]
Thank you @oegedijk,

It was a very helpful suggestion. 
I was able to create a table by editing the class DisplayIndex above as below based on your suggestion.
I also used explainer.get_X_row(index) using the selected index to call a row to create the table.

    class DisplayTable(ExplainerComponent):
    def __init__(self, title="Selected Data Table", name=None, index_selector=None):
        super().__init__(explainer, title, name)
        self.exclude_callbacks(index_selector)

    def layout(self):
        return dbc.Card([
            dbc.CardHeader([
                html.Div([
                    html.H3(self.title, className='card-title'),
                ]), 
            ]),
            dbc.CardBody([
                dbc.Row([
                    dbc.Col([
                        html.Div(id='displayindex-div-'+self.name)
                    ])
                ]),
            ])
        ])

    def component_callbacks(self, app):
        if self.index_selector is not None:
            @app.callback(
                Output('displayindex-div-'+self.name, 'children'),
                [Input(self.index_selector.index_name, 'value')])
            def update_output_div(index):
                df_X_row = explainer.get_X_row(index)
                return DataTable(
                                # id='predictions-table-table-'+self.name,
                                columns=[{"name": i, "id": i, 
                                        # 'deletable': True
                                        } for i in (df_X_row.columns.tolist())],
                                # data=None,
                                data=df_X_row.to_dict('records'),
                                editable=True,
                                filter_action="native",
                                sort_action="native",
                                sort_mode="multi",
                                page_action="native",
                                page_current= 0,
                                page_size= 10,
                                # style table and cells
                                style_table={
                                    'overflowX': 'auto', 
                                },
                                style_cell={
                                    'height': 'auto',
                                    'whiteSpace': 'normal'
                                },
                            ),
