### ISSUE TITLE
Possibility of Feeding Other Data than Data Used for Training

### ISSUE THREAD

**Issue by matt-song27** [oegedijk/explainerdashboard#104]
In addition to input data and model, we want to feed another data frame to explainerdashboard. 
Is it possible?

For instance, 
We used age and smoking history (yes or no) to predict an event using a classification model. 
Can we provide input data that has other columns like BMI, Gender as an input to classifier?

**Comment by oegedijk** [comment]
Hi @matt-song27,

Generally, when you train a model on certain features then it expects the exact same input format in the test set (or production).

However, an alternative is using feature hashing such as in vowpal wabbit: https://github.com/VowpalWabbit/vowpal_wabbit

However that is currently not supported by the library, so short answer is: no.
