### ISSUE TITLE
Improvement: Ability to use other backends besides Flask f.ex. FastAPI

### ISSUE THREAD

**Issue by jruokolainen** [oegedijk/explainerdashboard#105]
Hi I'm playing with deployment of ExplainerDashboard. Would it be possible to support other backends besides Flask in the future. F.ex. I want to deploy to GCP and use oauth so I had a previous FastAPI script as a base with implemented oauth. But eventhough I can deploy the ExplainerHub with this although the hub itself runs in a different port and the authentication isn't connected to the FastAPI oauth. This is a problem, at the minimum provide an example where you route f.ex. oauth authentication from flask to the explainerhub

**Comment by oegedijk** [comment]
Hi @jruokolainen, 

Supporting backends besides Flask will be somewhat difficult given that dash itself is quite strongly coupled with Flask. Although it does seem in principle possible: https://github.com/rusnyder/fastapi-plotly-dash

Getting an oauth example working would be nice. Haven't worked with oauth myself, so would take some time to get to work. If you want to give it a try would be welcome!

**Comment by jruokolainen** [comment]
> Hi @jruokolainen,
> 
> Supporting backends besides Flask will be somewhat difficult given that dash itself is quite strongly coupled with Flask. Although it does seem in principle possible: https://github.com/rusnyder/fastapi-plotly-dash
> 
> Getting an oauth example working would be nice. Haven't worked with oauth myself, so would take some time to get to work. If you want to give it a try would be welcome!

I managed to get it mounted correctly  to root through fastAPI, I will write an example once I'm through with mounting to other endpoints as well

**Comment by oegedijk** [comment]
Awesome! Once you have an example we can see if we can integrate it into the library...

**Comment by jruokolainen** [comment]
I have the example ready, I could do a push for a new branch then see about the pull request

**Comment by oegedijk** [comment]
Awesome! Could you send a pull request?

**Comment by oegedijk** [comment]
Hi, if you have chance to submit a PR on this would be greatly appreciated!

**Comment by jruokolainen** [comment]
Sorry for the delay, I'll try to make a pull request next week!

**Comment by oegedijk** [comment]
No worries, we're not getting paid for this after all :) 

Also the code has changed a bit with the `/add_dashboard` route that allows you to add dashboards to the hub using a URL route. Not sure how hard that would be to implement in fastAPI, but otherwise maybe we could make it only supported with Flask.

**Comment by fcas** [comment]
Any news about fastapi support?

**Comment by oegedijk** [comment]
@fcas I havent had time to have a look at it. But if you have some time I'm happy to accept a PR!
