### ISSUE TITLE
How to set plot_type to compact dot for the shap.summary_plots?

### ISSUE THREAD

**Issue by hugocool** [oegedijk/explainerdashboard#106]
When running explainerdashboard the resulting summary_plots are only bar plots, while the beeswarm compact_dot plots are much more informative.

How could one pass the kw plot_type=compact_dot to the shap.summary_plot arguments?

**Comment by oegedijk** [comment]
Hi @hugocool,

Yes, this is possible! In general you can find all setting parameters in the explainer components documentation, e.g. for the `ShapSummaryComponent`: https://explainerdashboard.readthedocs.io/en/latest/components.html#shapsummarycomponent

All `**kwargs` from `ExplainerDashboard` get passed down through the components, so you can start the dashboard with:

```
ExplainerDashboard(explainer, summary_type='detailed', hide_type=True).run()
```

**Comment by tonydengpace** [comment]
@hugocool, did you successfully pass the argument to plot the dot for shap summary plot? I tried but I cannot make it.

**Comment by hugolytics** [comment]
Nope, because it wasn't implemented at the time idk about now.
However, I extracted the code from the SHAP library to make these types of plots work in explainerdashboard.
Basically, what you should know is that due to the way the API in SHAP is build, it is impossible to reproduce the SHAP plots in plotly instead of matplotlib. So any plots you want to use in explainerdashboard need to reimplement the SHAP code in plotly.
This is not impossible, but the SHAP code is frankly very poorly written with very little OOP.

So if you'd like we could make a contribution and develop these plots. I can open an issue and we can discuss the implementation. I'll share my work thus far.

**Comment by tonydengpace** [comment]
Hi @hugocool. Very appreciated your quick and detailed response. I just tried the latest version 0.3.7, but I got the same findings as yours. It seems that the lib didn't support it. However, it is interesting to see the dot_based summary plot in the official documentation: https://explainerdashboard.readthedocs.io/en/latest/components.html#shapsummarycomponent. 

For sure, it would be great if you could contribute and share your work. It is my pleasure to discuss the implementation. I totally agree that the doc-based beeswarm plot is more informative, we could observe the positive/negative impact on that.

**Comment by hugocool** [comment]
Sorry for the late reply, i found the colab notebook where I was working on the plot and stored the code in this gist.

https://gist.github.com/hugocool/8fec6bc6114a6ad1eac61ad8cee67989

If we can get the plot to work nicely in the cell we can open a pull request and finish the work in an IDE, but I found it a little easier to use colab to view all the intermediary plotting results (although debugging is quite painful, and vscode just started to allow debugging in notebooks, so we could move there).

Dont hesitate to reach out for discussion, i'd love to finish this feature it is sorely needed!

**Comment by tonydengpace** [comment]
Thanks very much for your share!


From: Hugo ***@***.***>
Sent: Wednesday, February 2, 2022 8:36 AM
To: oegedijk/explainerdashboard ***@***.***>
Cc: Deng, Tony (PACE) ***@***.***>; Comment ***@***.***>
Subject: [External] Re: [oegedijk/explainerdashboard] How to set plot_type to compact dot for the shap.summary_plots? (#106)


Sorry for the late reply, i found the colab notebook where I was working on the plot and stored the code in this gist.

https://gist.github.com/hugocool/8fec6bc6114a6ad1eac61ad8cee67989<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgist.github.com%2Fhugocool%2F8fec6bc6114a6ad1eac61ad8cee67989&data=04%7C01%7Ctony.deng%40riotinto.com%7C88c15eab31634af99be908d9e650f81a%7C4341df80fbe641bf89b0e6e2379c9c23%7C0%7C0%7C637794057706168004%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=iW%2FWNMU46X6yuNO3rYhv09fel%2FkVwaiXqcku4WADHSY%3D&reserved=0>

If we can get the plot to work nicely in the cell we can open a pull request and finish the work in an IDE, but I found it a little easier to use colab to view all the intermediary plotting results (although debugging is quite painful, and vscode just started to allow debugging in notebooks, so we could move there).

Dont hesitate to reach out for discussion, i'd love to finish this feature it is sorely needed!

-
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Foegedijk%2Fexplainerdashboard%2Fissues%2F106%23issuecomment-1027947822&data=04%7C01%7Ctony.deng%40riotinto.com%7C88c15eab31634af99be908d9e650f81a%7C4341df80fbe641bf89b0e6e2379c9c23%7C0%7C0%7C637794057706168004%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=EvBDuABxcyr0p%2FgQY65r9iVQFwuGFpo9Vk3%2FOj8ZgjE%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPXHMC7AWVAL64AWAVNQC23UZEXMRANCNFSM42NPCV7Q&data=04%7C01%7Ctony.deng%40riotinto.com%7C88c15eab31634af99be908d9e650f81a%7C4341df80fbe641bf89b0e6e2379c9c23%7C0%7C0%7C637794057706168004%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=pUUoX6Vz6z%2Bb%2FR2B4Wt308P8ST1jp1L80nKXuWwDA14%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ctony.deng%40riotinto.com%7C88c15eab31634af99be908d9e650f81a%7C4341df80fbe641bf89b0e6e2379c9c23%7C0%7C0%7C637794057706168004%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Sl%2B69CTuSRfwX0Y6%2BUaztznpgExEoyGr%2Ba2y9eOiB40%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ctony.deng%40riotinto.com%7C88c15eab31634af99be908d9e650f81a%7C4341df80fbe641bf89b0e6e2379c9c23%7C0%7C0%7C637794057706168004%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=GXrtqb2KAYB5lu7Ke9T0oDpe8Rya5GY%2BAGvMDcMPXwg%3D&reserved=0>.
