### ISSUE TITLE
Issue with ExplainerDashboard for Random Forest Classifier

### ISSUE THREAD

**Issue by teetysasithorn** [oegedijk/explainerdashboard#108]
I tried to get my ExplainerDashboard for Random Forest Classifier but it keeps showing the error.

`Exception: Additivity check failed in TreeExplainer! Please ensure the data matrix you passed to the explainer is the same shape that the model was trained on. If your data shape is correct then please report this on GitHub. This check failed because for one of the samples the sum of the SHAP values was 0.367523, while the model output was 0.370737. If this difference is acceptable you can set check_additivity=False to disable this check.`

I'm pretty sure that my data is in the same shape that the model was trained on. Where do I put 'check_additivity=False'?

**Comment by oegedijk** [comment]
Hi @teetysasithorn,

Hmm, that looks like a numerical instability error. Usually when I get this error the sum of SHAPs is way off and there is a real bug somewhere. This team it just looks like a rounding error? Does it reproduce?



The `check_additivity=False` flag would go into the shap_values command, e.g.:

```python
exp = shap.TreeExplainer(model)
shap_values = exp.shap_values(X_test, check_additivity=False)
```

In the library this happens in the method `get_shap_values_df()`, so if you want to disable you could monkeypatch it:

https://github.com/oegedijk/explainerdashboard/blob/d46b8fc5228f6fd6a6fbb2d3cf5da33488af3cda/explainerdashboard/explainers.py#L887
