### ISSUE TITLE
ExplainerDashboard - AttributeError: 'list' object has no attribute 'keys'

### ISSUE THREAD

**Issue by pit9921** [oegedijk/explainerdashboard#111]
i can't figure out, why i get the following error:  AttributeError: 'list' object has no attribute 'keys'.
The dashboard works, but the menus: feature importances and SHAP Summary in Feature Dependence menu not.

```
explainer = RegressionExplainer(final_best, X_test, y_test, 
                                descriptions = feature_descriptions,
                                target='Durchmesser',
                                units="mm")
```

![1](https://user-images.githubusercontent.com/77811022/115773395-8bcd6f00-a3b0-11eb-9f78-c230eaa5250b.png)
![2](https://user-images.githubusercontent.com/77811022/115773396-8cfe9c00-a3b0-11eb-805f-c72b935ee238.png)
![3](https://user-images.githubusercontent.com/77811022/115773401-8d973280-a3b0-11eb-90e5-59811abb020d.png)
![4](https://user-images.githubusercontent.com/77811022/115773403-8e2fc900-a3b0-11eb-88f6-66920b3e550f.png)

The same error i get for all features in dataframe:

AttributeError                            Traceback (most recent call last)
~\anaconda3\lib\site-packages\explainerdashboard\dashboard_components\overview_components.py in update_importances(
    depth=None,
    permutation_shap='shap',
    pos_label=None
)
    245         def update_importances(depth, permutation_shap, pos_label):
    246             depth = None if depth is None else int(depth)
--> 247             plot =  self.explainer.plot_importances(
        plot = undefined
        global self.explainer.plot_importances = undefined
        global kind = undefined
        permutation_shap = 'shap'
        global topx = undefined
        depth = None
        pos_label = None
    248                         kind=permutation_shap, topx=depth, pos_label=pos_label)
    249             return plot

~\anaconda3\lib\site-packages\explainerdashboard\explainers.py in inner(
    self=<explainerdashboard.explainers.RegressionExplainer object>,
    *args=(),
    **kwargs={'kind': 'shap', 'pos_label': None, 'topx': None}
)
     46     def inner(self, *args, **kwargs):
     47         if not self.is_classifier:
---> 48             return func(self, *args, **kwargs)
        global func = undefined
        self = <explainerdashboard.explainers.RegressionExplainer object at 0x000001EC4798DEB0>
        args = ()
        kwargs = {'kind': 'shap', 'topx': None, 'pos_label': None}
     49         if 'pos_label' in kwargs:
     50             if kwargs['pos_label'] is not None:

~\anaconda3\lib\site-packages\explainerdashboard\explainers.py in plot_importances(
    self=<explainerdashboard.explainers.RegressionExplainer object>,
    kind='shap',
    topx=None,
    round=3,
    pos_label=None
)
   1423             units = ""
   1424         if self.descriptions:
-> 1425             descriptions = self.description_list(importances_df.Feature)
        descriptions = undefined
        self.description_list = <bound method BaseExplainer.description_list of <explainerdashboard.explainers.RegressionExplainer object at 0x000001EC4798DEB0>>
        importances_df.Feature = 0      ESD
1      NDZ
2      NDH
3    WTemp
4       LF
5    UTemp
6    MTemp
7      KUZ
Name: Feature, dtype: object
   1426             return plotly_importances_plot(importances_df, descriptions, round=round, units=units, title=title)
   1427         else:

~\anaconda3\lib\site-packages\explainerdashboard\explainers.py in description_list(
    self=<explainerdashboard.explainers.RegressionExplainer object>,
    cols=0      ESD
1      NDZ
2      NDH
3    WTemp
4   ...    MTemp
7      KUZ
Name: Feature, dtype: object
)
    724             list of descriptions
    725         """
--> 726         return [self.description(col) for col in cols]
        self.description = <bound method BaseExplainer.description of <explainerdashboard.explainers.RegressionExplainer object at 0x000001EC4798DEB0>>
        global col = undefined
        cols = 0      ESD
1      NDZ
2      NDH
3    WTemp
4       LF
5    UTemp
6    MTemp
7      KUZ
Name: Feature, dtype: object
    727 
    728     def ordered_cats(self, col, topx=None, sort='alphabet', pos_label=None):

~\anaconda3\lib\site-packages\explainerdashboard\explainers.py in <listcomp>(.0=<map object>)
    724             list of descriptions
    725         """
--> 726         return [self.description(col) for col in cols]
        global self.description = undefined
        col = 'ESD'
        global cols = undefined
    727 
    728     def ordered_cats(self, col, topx=None, sort='alphabet', pos_label=None):

~\anaconda3\lib\site-packages\explainerdashboard\explainers.py in description(
    self=<explainerdashboard.explainers.RegressionExplainer object>,
    col='ESD'
)
    711             str, description
    712         """
--> 713         if col in self.descriptions.keys():
        col = 'ESD'
        self.descriptions.keys = undefined
    714             return self.descriptions[col]
    715         return ""

AttributeError: 'list' object has no attribute 'keys'

**Comment by oegedijk** [comment]
Hi, sorry for just getting back to me now. Anyway, descriptions should be a dictionary: keys are the name of the feature, and values the long description for that feature. It seems you passed a list instead of a dictionary and hence the error.
