### ISSUE TITLE
ClassifierExplainer calling 'unique' attribute on actual dataframe instead of dataframe[column] in categorical encoding

### ISSUE THREAD

**Issue by darreltrinh** [oegedijk/explainerdashboard#113]
I am trying to push a cross validated model into ClassifierExplainer with the following code in Jupyter Notebook:

Create Test/Train

`x_train,x_test,y_train,y_test = train_test_split(features,target,test_size = 0.3, random_state = 42)`

Call Random Forest

`clf = RandomForestClassifier(random_state=42)`

Create CV parameters

```
from sklearn.model_selection import RandomizedSearchCV
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
max_features = ['auto', 'sqrt']
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
min_samples_split = [2, 5, 10]
min_samples_leaf = [1, 2, 4]
bootstrap = [True, False]
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}
```

Tune and fit model

```
clf_tune = RandomizedSearchCV(estimator = clf, 
                              param_distributions=random_grid,
                              n_iter=100,
                              cv=3,
                              verbose=2,
                              random_state=42,
                              n_jobs=-1)
clf_tune.fit(x_train,y_train)
```
Push model to Classifier Explainer following documentation
```
from explainerdashboard import ClassifierExplainer, ExplainerDashboard
explainer = ClassifierExplainer(clf_tune, x_test, y_test)
```

I get the following error (screenshot attached) when running the ClassifierExplainer cell in Jupyter.
![Screen Shot 2021-04-29 at 12 54 38 PM](https://user-images.githubusercontent.com/22823385/116603348-11d64200-a8ea-11eb-97f1-48be50235834.png)

It looks like self.categorical_dict isn't calling the columns correctly and is calling the dataframe instead of the column. My dataset doesn't have any categorical variables and I would ideally like to turn it off, but am wondering if there is a work around or if I'm using the library incorrectly. Any insight would be appreciated as I am not sure how to troubleshoot this further

**Comment by oegedijk** [comment]
Hi @darreltrinh,

As you can see in the code with the error I detect numeric columns with the pandas helper function `is_numeric_dtype()`.

Could you try

```python
from pandas.api.types import is_numeric_dtype

for col in x_test.columns:
  if not is_numeric_dtype(x_test[col]):
    print(f"Found categorical column: {col} ")
```

to see which columns appear to be categorical in this way?

Also, I would guess that you would have to pass `clf_tune.best_estimator_` to the Explainer, as that is the actual model instance.

**Comment by darreltrinh** [comment]
Thanks for getting back to me @oegedijk. Thanks for sending that over it was super helpful. Turns out my SQL aliasing was off and duplicated a column name thus triggering that error. Was able to instantiate the explainer and now trying to run the Dashboard. 

I'm going to go ahead and close this out! Issue looks to be resolved!
