### ISSUE TITLE
detailed summary type does not work: Callback error updating interaction-summary-graph

### ISSUE THREAD

**Issue by hugocool** [oegedijk/explainerdashboard#116]
in explainerdashboard version 0.34

when using the detailed summary type on the XGBRegressionExplainer
i get the following error (in dash):

Callback error updating interaction-summary-graph-60.figure, interaction-summary-index-col-60.style
17:56:37
Callback error updating interaction-summary-graph-60.figure, 
interaction-summary-index-col-60.style

![image](https://user-images.githubusercontent.com/25592581/116900807-74f10d00-ac39-11eb-8bf8-ec9e3276dd63.png)

code to replicate:

```
from sklearn.datasets import load_diabetes
import pandas as pd

data = load_diabetes()
X = pd.DataFrame(data = data['data'],columns = data['feature_names'])
y = data['target']

from xgboost import XGBRegressor

sklearnxgbr = XGBRegressor()
sklearnxgbr.fit(X,y)

from explainerdashboard.explainers import XGBRegressionExplainer
from explainerdashboard import ExplainerDashboard

explainer = XGBRegressionExplainer(sklearnxgbr, X,y)

ExplainerDashboard(explainer, 
                  summary_type='detailed', 
                  ).run()


```

All the other plots do work, including the aggregate summary plot but not the detailed (compact_dot) feature dependency and interaction summary plots

**Comment by oegedijk** [comment]
Hi,

First off you don't need to explicitly use the `XGBRegressionExplainer`: the xgboost model get's autodetected and then the explainer gets recast, so you can simply use `RegressionExplainer(sklearnxgbr, X, y)`.

Could you try to just run in a notebook to see if the plots work: 
```
explainer.plot_importances_detailed()
```

And 
```
col = X.columns.tolist()[0] # or just replace by a column of choice
explainer.plot_interactions_detailed(col)
```

Would be useful to see if it is a plot generation error or a dash internal error

**Comment by hugocool** [comment]
`
explainer.plot_importances_detailed()
`
gives the following error:

> Calculating shap values...
> ---------------------------------------------------------------------------
> IndexError                                Traceback (most recent call last)
> /usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py in _get_list_axis(self, key, axis)
>    1468         try:
> -> 1469             return self.obj._take_with_is_copy(key, axis=axis)
>    1470         except IndexError as err:
> 
> 9 frames
> /usr/local/lib/python3.7/dist-packages/pandas/core/generic.py in _take_with_is_copy(self, indices, axis)
>    3362         """
> -> 3363         result = self.take(indices=indices, axis=axis)
>    3364         # Maybe set copy if we didn't actually change the index.
> 
> /usr/local/lib/python3.7/dist-packages/pandas/core/generic.py in take(self, indices, axis, is_copy, **kwargs)
>    3350         new_data = self._mgr.take(
> -> 3351             indices, axis=self._get_block_manager_axis(axis), verify=True
>    3352         )
> 
> /usr/local/lib/python3.7/dist-packages/pandas/core/internals/managers.py in take(self, indexer, axis, verify, convert)
>    1448         if convert:
> -> 1449             indexer = maybe_convert_indices(indexer, n)
>    1450 
> 
> /usr/local/lib/python3.7/dist-packages/pandas/core/indexers.py in maybe_convert_indices(indices, n)
>     249     if mask.any():
> --> 250         raise IndexError("indices are out-of-bounds")
>     251     return indices
> 
> IndexError: indices are out-of-bounds
> 
> The above exception was the direct cause of the following exception:
> 
> IndexError                                Traceback (most recent call last)
> <ipython-input-11-93b27e22e2e9> in <module>()
> ----> 1 explainer.plot_importances_detailed()
> 
> /usr/local/lib/python3.7/dist-packages/explainerdashboard/explainers.py in inner(self, *args, **kwargs)
>      46     def inner(self, *args, **kwargs):
>      47         if not self.is_classifier:
> ---> 48             return func(self, *args, **kwargs)
>      49         if 'pos_label' in kwargs:
>      50             if kwargs['pos_label'] is not None:
> 
> /usr/local/lib/python3.7/dist-packages/explainerdashboard/explainers.py in plot_importances_detailed(self, highlight_index, topx, max_cat_colors, plot_sample, pos_label)
>    1472 
>    1473         return plotly_shap_scatter_plot(
> -> 1474                                 self.X_merged[cols].iloc[plot_idxs],
>    1475                                 self.get_shap_values_df(pos_label)[cols].iloc[plot_idxs],
>    1476                                 cols,
> 
> /usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py in __getitem__(self, key)
>     877 
>     878             maybe_callable = com.apply_if_callable(key, self.obj)
> --> 879             return self._getitem_axis(maybe_callable, axis=axis)
>     880 
>     881     def _is_scalar_access(self, key: Tuple):
> 
> /usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py in _getitem_axis(self, key, axis)
>    1485         # a list of integers
>    1486         elif is_list_like_indexer(key):
> -> 1487             return self._get_list_axis(key, axis=axis)
>    1488 
>    1489         # a single integer
> 
> /usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py in _get_list_axis(self, key, axis)
>    1470         except IndexError as err:
>    1471             # re-raise with different error message
> -> 1472             raise IndexError("positional indexers are out-of-bounds") from err
>    1473 
>    1474     def _getitem_axis(self, key, axis: int):
> 
> IndexError: positional indexers are out-of-bounds

while 
`
explainer.plot_importances()
`
simply works

the second function you mentioned:

```
col = X.columns.tolist()[0]
explainer.plot_interactions_detailed(col)
```


gives the following traceback:

> Calculating shap interaction values...
> Reminder: TreeShap computational complexity is O(TLD^2), where T is the number of trees, L is the maximum number of leaves in any tree and D the maximal depth of any tree. So reducing these will speed up the calculation.
> ---------------------------------------------------------------------------
> IndexError                                Traceback (most recent call last)
> /usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py in _get_list_axis(self, key, axis)
>    1468         try:
> -> 1469             return self.obj._take_with_is_copy(key, axis=axis)
>    1470         except IndexError as err:
> 
> 9 frames
> /usr/local/lib/python3.7/dist-packages/pandas/core/generic.py in _take_with_is_copy(self, indices, axis)
>    3362         """
> -> 3363         result = self.take(indices=indices, axis=axis)
>    3364         # Maybe set copy if we didn't actually change the index.
> 
> /usr/local/lib/python3.7/dist-packages/pandas/core/generic.py in take(self, indices, axis, is_copy, **kwargs)
>    3350         new_data = self._mgr.take(
> -> 3351             indices, axis=self._get_block_manager_axis(axis), verify=True
>    3352         )
> 
> /usr/local/lib/python3.7/dist-packages/pandas/core/internals/managers.py in take(self, indexer, axis, verify, convert)
>    1448         if convert:
> -> 1449             indexer = maybe_convert_indices(indexer, n)
>    1450 
> 
> /usr/local/lib/python3.7/dist-packages/pandas/core/indexers.py in maybe_convert_indices(indices, n)
>     249     if mask.any():
> --> 250         raise IndexError("indices are out-of-bounds")
>     251     return indices
> 
> IndexError: indices are out-of-bounds
> 
> The above exception was the direct cause of the following exception:
> 
> IndexError                                Traceback (most recent call last)
> <ipython-input-14-71d71a900250> in <module>()
>       1 col = X.columns.tolist()[0] # or just replace by a column of choice
> ----> 2 explainer.plot_interactions_detailed(col)
> 
> /usr/local/lib/python3.7/dist-packages/explainerdashboard/explainers.py in inner(self, *args, **kwargs)
>      46     def inner(self, *args, **kwargs):
>      47         if not self.is_classifier:
> ---> 48             return func(self, *args, **kwargs)
>      49         if 'pos_label' in kwargs:
>      50             if kwargs['pos_label'] is not None:
> 
> /usr/local/lib/python3.7/dist-packages/explainerdashboard/explainers.py in plot_interactions_detailed(self, col, highlight_index, topx, max_cat_colors, plot_sample, pos_label)
>    1719         title = f"Shap interaction values for {col}"
>    1720         return plotly_shap_scatter_plot(
> -> 1721                 self.X_merged.iloc[plot_idxs], shap_df, interact_cols[:topx], title=title,
>    1722                 idxs=self.idxs[plot_idxs], highlight_index=highlight_index, na_fill=self.na_fill,
>    1723                 max_cat_colors=max_cat_colors)
> 
> /usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py in __getitem__(self, key)
>     877 
>     878             maybe_callable = com.apply_if_callable(key, self.obj)
> --> 879             return self._getitem_axis(maybe_callable, axis=axis)
>     880 
>     881     def _is_scalar_access(self, key: Tuple):
> 
> /usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py in _getitem_axis(self, key, axis)
>    1485         # a list of integers
>    1486         elif is_list_like_indexer(key):
> -> 1487             return self._get_list_axis(key, axis=axis)
>    1488 
>    1489         # a single integer
> 
> /usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py in _get_list_axis(self, key, axis)
>    1470         except IndexError as err:
>    1471             # re-raise with different error message
> -> 1472             raise IndexError("positional indexers are out-of-bounds") from err
>    1473 
>    1474     def _getitem_axis(self, key, axis: int):
> 
> IndexError: positional indexers are out-of-bounds

while

`
col = X.columns.tolist()[0] # or just replace by a column of choice
explainer.plot_interactions_importance(col)
`
just works

**Comment by Verkenner** [comment]
I think I have the same problem with Titanic Data.

Start code:

from sklearn.ensemble import RandomForestClassifier
from explainerdashboard import ClassifierExplainer, ExplainerDashboard
from explainerdashboard.datasets import titanic_survive, titanic_names

X_train, y_train, X_test, y_test = titanic_survive()
ExplainerDashboard(ClassifierExplainer(RandomForestClassifier().fit(X_train, y_train), X_test, y_test)).run()

End code

When I select 'Detailed' for 'Summary Type' in tab 'Feature Dependence', I get the following error:

192.168.0.111 - - [04/May/2021 16:25:23] "POST /_dash-update-component HTTP/1.1" 200 -
192.168.0.111 - - [04/May/2021 16:27:06] "POST /_dash-update-component HTTP/1.1" 500 -
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\Users\holdi\PycharmProjects\FirstProject\venv\lib\site-packages\pandas\core\indexing.py", line 1469, in _get_list_axis
    return self.obj._take_with_is_copy(key, axis=axis)
  File "C:\Users\holdi\PycharmProjects\FirstProject\venv\lib\site-packages\pandas\core\generic.py", line 3363, in _take_with_is_copy
    result = self.take(indices=indices, axis=axis)
  File "C:\Users\holdi\PycharmProjects\FirstProject\venv\lib\site-packages\pandas\core\generic.py", line 3351, in take
    indices, axis=self._get_block_manager_axis(axis), verify=True
  File "C:\Users\holdi\PycharmProjects\FirstProject\venv\lib\site-packages\pandas\core\internals\managers.py", line 1449, in take
    indexer = maybe_convert_indices(indexer, n)
  File "C:\Users\holdi\PycharmProjects\FirstProject\venv\lib\site-packages\pandas\core\indexers.py", line 250, in maybe_convert_indices
    raise IndexError("indices are out-of-bounds")
IndexError: indices are out-of-bounds

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\holdi\PycharmProjects\FirstProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\holdi\PycharmProjects\FirstProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\holdi\PycharmProjects\FirstProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\holdi\PycharmProjects\FirstProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\holdi\PycharmProjects\FirstProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\holdi\PycharmProjects\FirstProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\holdi\PycharmProjects\FirstProject\venv\lib\site-packages\dash\dash.py", line 1079, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "C:\Users\holdi\PycharmProjects\FirstProject\venv\lib\site-packages\dash\dash.py", line 1010, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "C:\Users\holdi\PycharmProjects\FirstProject\venv\lib\site-packages\explainerdashboard\dashboard_components\shap_components.py", line 177, in update_shap_summary_graph
    max_cat_colors=self.max_cat_colors, plot_sample=self.plot_sample)
  File "C:\Users\holdi\PycharmProjects\FirstProject\venv\lib\site-packages\explainerdashboard\explainers.py", line 53, in inner
    return func(self, *args, **kwargs)
  File "C:\Users\holdi\PycharmProjects\FirstProject\venv\lib\site-packages\explainerdashboard\explainers.py", line 1474, in plot_importances_detailed
    self.X_merged[cols].iloc[plot_idxs],
  File "C:\Users\holdi\PycharmProjects\FirstProject\venv\lib\site-packages\pandas\core\indexing.py", line 879, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "C:\Users\holdi\PycharmProjects\FirstProject\venv\lib\site-packages\pandas\core\indexing.py", line 1487, in _getitem_axis
    return self._get_list_axis(key, axis=axis)
  File "C:\Users\holdi\PycharmProjects\FirstProject\venv\lib\site-packages\pandas\core\indexing.py", line 1472, in _get_list_axis
    raise IndexError("positional indexers are out-of-bounds") from err
IndexError: positional indexers are out-of-bounds

**Comment by oegedijk** [comment]
Ah, found it! There was a bug when you don't define any onehot encoded columns. Fixed it, will try to get a new release out tomorrow.

So this fails:

```
from sklearn.ensemble import RandomForestClassifier
from explainerdashboard import ClassifierExplainer, ExplainerDashboard
from explainerdashboard.datasets import titanic_survive, titanic_names

X_train, y_train, X_test, y_test = titanic_survive()
explainer = ClassifierExplainer(RandomForestClassifier().fit(X_train, y_train), X_test, y_test)
ExplainerDashboard(explainer).run()
```

but this should work:
```
from sklearn.ensemble import RandomForestClassifier
from explainerdashboard import ClassifierExplainer, ExplainerDashboard
from explainerdashboard.datasets import titanic_survive, titanic_names

X_train, y_train, X_test, y_test = titanic_survive()
explainer = ClassifierExplainer(RandomForestClassifier().fit(X_train, y_train), X_test, y_test, 
                                cats=['Sex', 'Deck', 'Embarked'])
ExplainerDashboard(explainer).run()
```

**Comment by oegedijk** [comment]
Just pushed the fix to a release: https://github.com/oegedijk/explainerdashboard/releases/tag/v0.3.4.1

If you `pip install -U explainerdashboard` it should now work?

(conda will take a bit longer to get the update)

**Comment by hugocool** [comment]
Hi @oegedijk , it definitely works!

many thanks!
