### ISSUE TITLE
Mlflow/ExplainerDashboard integration difficulties, might be due to dash integration in iframe ?

### ISSUE THREAD

**Issue by Simon-Free** [oegedijk/explainerdashboard#119]
Hi !

Just to notify, I do have a problem integrating dash dashboards (and thus explainerdashboard). The main problem seems to be the integration of a dash dashboard in an iframe. Not sure if you can help, but if you have encountered the problem, and have any idea why, that would be great 😄 ! (If not, no worries 😉)

Here is [the issue link](https://github.com/mlflow/mlflow/issues/4330)

**Comment by oegedijk** [comment]
Hi @Simon-Free did you manage to get this to work in the end?

**Comment by Simon-Free** [comment]
Sorry for late answer, I was in vacations. So, kind of, what I finally did was saving url links to my dashboards as artifacts, and launched a web server that opens the appropriate dashboard, depending on the URL. To do the following, I used something like this:

````python
from flask import Flask
import flask
from explainerdashboard import ExplainerDashboard
from flask import request, redirect

def init_app():
    """Construct core Flask application with embedded Dash app."""
    app = Flask(__name__, static_url_path="")

    with app.app_context() as apc:
        @app.before_request
        def new_dashboard():
            # request.path contains
            explainer_filename, dashboard_yaml_filename = retrieve_filename_from_request_url(request.path)
            db = ExplainerDashboard.from_config(
                explainer_filename,
                dashboard_yaml_filename,
                server=flask.current_app._LocalProxy__local(),  # IMPORTANT PART, you have to provide the current app
                url_base_pathname=f"/explainerdashboard/_{get_proxy_name(request.path)}/", #
                external_stylesheets=["/static/bootstrap.min.css"],
            )
            db.name = db_name
            return redirect(f"/explainerdashboard/_{get_proxy_name(request.path)}/", code=302)


if __name__ == '__main__':

    app = init_app()
    app.run(host="127.0.0.1", port="8050")
````

**Comment by oegedijk** [comment]
Okay, hope that workaround will help other people with the same issue. Thanks a lot! 

Closing for now...
