### ISSUE TITLE
Run with pre-computed SHAP values/interactions

### ISSUE THREAD

**Issue by e5k** [oegedijk/explainerdashboard#121]
Hello,

Getting familiar with your great tool, I was wondering how/if I could prevent computing SHAP values. I have already computed and saved SHAP values and interaction values on a GPU cluster and was wondering if there was a way to feed them to an `Explainer` and bypass their calculation when I run the explainer dashboard on my laptop.

Thanks a lot

**Comment by oegedijk** [comment]
Hi @e5k,

Yes, that is in principle possible in a somewhat hacky way: the shap values are stored internally in `self._shap_values_df`, which is simply the shap values wrapped in a dataframe with the right columns names. See the code for the general (i.e. regression) case here:

https://github.com/oegedijk/explainerdashboard/blob/07b433dff04155a0a278f5b97b31f6bdd6b37b03/explainerdashboard/explainers.py#L946

And for classifiers here:

https://github.com/oegedijk/explainerdashboard/blob/07b433dff04155a0a278f5b97b31f6bdd6b37b03/explainerdashboard/explainers.py#L2264

As you can see especially for multi class classifiers there is a bit more involved, but for a RegressionExplainer you could squeeze in your pre-calculated shap values like this:

```python
sv  = shap.TreeExplainer(model).shap_values(X_test)
explainer = RegressionExplainer(model, X_test, y_test)
explainer._shap_values_df = pd.DataFrame(sv, columns=X_test.columns)
```

For a binary classifier, you just need to specify the positive class with `[1]`:

```python
sv  = shap.TreeExplainer(model).shap_values(X_test)[1]
explainer = RegressionExplainer(model, X_test, y_test)
explainer._shap_values_df = pd.DataFrame(sv, columns=X_test.columns)
```

If you have onehot encoded columns that you group together with the `cats` parameter you need to group the shap values with `merge_categorical_shap_values`:

```python
from explainerdashboard.explainer_methods import merge_categorical_shap_values

explainer = ClassifierExplainer(model, X_test, y_test, cats=['Sex', 'Deck', 'Embarked'])
explainer._shap_values_df = pd.DataFrame(sv, columns=X_test.columns)
explainer._shap_values_df = merge_categorical_shap_values(explainer._shap_values_df, explainer.onehot_dict, explainer.merged_cols)
```

However especially with large models that can be calculated on GPUs I can see how it would be a useful feature to make this easier by exposing a method that does this for the user.

**Comment by e5k** [comment]
Hi @oegedijk,

Thanks a lot for your answer. I will get back on this project next week and will try your trick - keep you updated! Ill see if I can do something to add the feature, but that might be beyond me

**Comment by e5k** [comment]
Hello @oegedijk ,

Getting back to you only now ^_^ to let you know your hack worked like a charm. Is there a similar approach to feed Shap interaction values?

**Comment by e5k** [comment]
Hey @oegedijk ,

After doing a few tests, the SHAP values entered manually don't make much sense. I calculate the SHAP values following [this example](https://xgboost.readthedocs.io/en/latest/gpu/index.html#gpu-accelerated-shap-values) and then input these shape values in the explainer. Attached are two pictures, the first showing SHAP values computed by the explainer, the second showing pre-computed Shap values entered with your suggestion.

Can you make any sense of that? I am messing up things?

Alternatively, is there any way to activate SHAP's `GPUTree` explainer?

Thanks a lot

<img width="483" alt="Screenshot 2021-09-17 at 10 20 17" src="https://user-images.githubusercontent.com/16320236/133749722-8d179a6c-5e63-4281-ba0c-381655f979b8.png">
<img width="490" alt="Screenshot 2021-09-17 at 09 47 32" src="https://user-images.githubusercontent.com/16320236/133749732-216387f2-552e-4b88-9c78-6715c9b96f4a.png">

**Comment by oegedijk** [comment]
Hey, forgot to loop back on this, but actually added methods `explainer.set_shap_values()` and `explainer.set_shap_interaction_values()` that allow you to import pre-calculated shap values in the last release. 

Could you test if these work for you?

**Comment by e5k** [comment]
Thanks a lot for that! I unfortunately had to move on, so I ended up running the whole explorer from the GPU, computing the SHAP values there instead of through the XGBoost library, then saving it and running it back locally. I will try it at some point - hopefully soon, but many thanks for the update!
