### ISSUE TITLE
Calling n_jobs method

### ISSUE THREAD

**Issue by Manuelhrokr** [oegedijk/explainerdashboard#122]
Hello, 

Thank you so much for this great tool you've developed. I would like to ask if the **n_jobs**  argument works the same as in Scikit-learn (i.e. **RandomForestClassifier class**), by passing **-1** if we want to use all the available cores. I've run some tests by passing this arg as **-1** to the **ClassifierExplainer class**  but I can't see the job is being parallelised. 

I hope you can help me.

Thanks,
Manuel

**Comment by oegedijk** [comment]
Hi @Manuelhrokr,

There are not that many under the hood methods that currently actually use the `n_jobs` attribute (mainly calculated permutation importance), but in principle passing `-1` should work as the parameter is simply passed to `joblib.Parallel()`.
