### ISSUE TITLE
Allow for passing of the normalized argument to the confusion matrix plot

### ISSUE THREAD

**Issue by hugocool** [oegedijk/explainerdashboard#124]
The normalisation for the confusion matrix plot displayed in percentages is calculated over all the observations in the dataset, or  'all' in terms of its sklearn equivalent.
This causes confusion with stakeholder, who easily misinterpret accurate algorithms on imbalanced dataset to be inaccurate.
Currently the normalize keyword toggles whether the display order of the percentage vs the count.
I suggest to change this normalized keyword in the explainer to percentage and add an option to the component to choose a normalisation method in line with sklearns options (true, pred and all).
(with the option to toggle between these normalisations in the dashboard).
![Screenshot 2021-06-14 at 17 57 01](https://user-images.githubusercontent.com/25592581/121922934-b39adc80-cd3a-11eb-91b3-34e2378a1284.png)

**Comment by oegedijk** [comment]
merged the PR so closing this!
