### ISSUE TITLE
Label mismatch in horizontal contributions plot

### ISSUE THREAD

**Issue by hugocool** [oegedijk/explainerdashboard#126]
in the horizontally oriented contribution plot the hover over labels are reversed, this is caused by the following lines in explainer_plots.py

```
if orientation == 'horizontal':        
   cols = cols[::-1]        
   values = values[::-1]        
   contribs = contribs[::-1]        
   bases = bases[::-1]        
   fill_colors = fill_colors[::-1]        
   line_colors = line_colors[::-1]
```

which misses

`hover_text = hover_text[::-1]`

ill open a pull request for the bug fix

**Comment by oegedijk** [comment]
just merged the PR so closing this!
