### ISSUE TITLE
Heroku: Gunicorn not identifying custom module in Django Project

### ISSUE THREAD

**Issue by Ishsh2020** [oegedijk/explainerdashboard#127]
I am using a custom module in my Django app,when I tried to deploy this in Heroku, gunicorn is not detecting this module.

Here is my code in manage.py where I have imported the module

from defs import log_transform

Procfile is :

web gunicorn myapp.wsgi --log-file -

Am getting this error

Can't get attribute 'xxxxxx' on <module '__main__' from '/app/.heroku/python/bin/gunicorn'>

Should I make any changes in settings.py for adding this custom module?

Can someone please  help

**Comment by oegedijk** [comment]
Hi @Ishsh2020,

I have zero experience with django, so won't be much help here. If you figure out a fix do let us know in case others run into the same issue!
