### ISSUE TITLE
ValueError: could not convert string to float when creating dashboard for LGMBClassifier

### ISSUE THREAD

**Issue by amine-hef** [oegedijk/explainerdashboard#128]
Hi,
So I am having an error when I try to create an ExplainerDashboard.
I'm trying to make a dashboard for a LGBMClassifier model trained for multiclass classification, which takes as input some categorical features that are not one-hot encoded cause lgb doesn't need it and on top of that my categorical features have more than thousands of unique values.

That has been said I create the explainer like that:
explainer = ClassifierExplainer(
                model, encoded_X_val, y_val, shap='tree', model_output='logodds',
                # optional:
                labels=le.classes_)
I got a warning telling me that: 
Warning: Detected the following categorical columns: ['col1', 'col2', 'col3']. Unfortunately for now shap interaction values do not work withcategorical columns.

1) Is it possible to create a dashboard without interaction values of these categorical columns ?

Then I tried to create a Dashboard and I got this error :
![image](https://user-images.githubusercontent.com/32578022/123670901-fe8a1900-d83d-11eb-8289-6df915367aaa.png)
'FI' is a categorical values from 'col1'.

2) if answer to question 1 is yes, how can deal with this error ?

**Comment by oegedijk** [comment]
Hi @amine-hef,

For the warnings message: The interactions tab of the dashboard should get automatically disabled when you have categorical features.

For the error: could you show the full stack trace? It seems that there are is a place where the dashboard expects a float, but got a string instead...

**Comment by amine-hef** [comment]
Hi @oegedijk 
Here is the full stack.
![image](https://user-images.githubusercontent.com/32578022/124727891-6cee6b80-df0f-11eb-895c-1bfb9a2a5d34.png)
![image](https://user-images.githubusercontent.com/32578022/124728068-914a4800-df0f-11eb-805e-6f107e30b171.png)

**Comment by oegedijk** [comment]
Hi,

It seems the error occurs inside the `shap` library, where it calls the LGBM model to do a prediction with `pred_contrib=True`.

Have you tried running this directly?

**Comment by amine-hef** [comment]
Hi Oege,

Thanks for your help, so I finally made the trick to make the dashboard "working".

When I tried to do prediction with pred_contrib=True, I got no errors and when comparing with your code.
The difference was that I provided directly the X dataframe and not just the numpy representation.
![image](https://user-images.githubusercontent.com/32578022/127607493-caf23f90-4ccd-490f-b2b4-5d3b7eb89bc4.png)
I checked shap documentation and it should also accept the numpy representation of the dataframe, idk why this error occur.

I've then assign the shap_values to the explainer myself and this make the dashboard launching !

But I got an error with plot_importances function.
![image](https://user-images.githubusercontent.com/32578022/127607924-cf1eb2c3-324b-40b6-a5f6-27da9a76d006.png)
Changing this : importance_df['Feature'].str.len().max() 
By this: max(importance_df['Feature'], key=len) 
Should do the trick :) !

**Comment by oegedijk** [comment]
> I checked shap documentation and it should also accept the numpy representation of the dataframe, idk why this error occur.

Hmm. this is weird, and so presumably a bug in shap. Did you open an issue there? 

I could see if I can pass a dataframe instead of the the underlying numpy array by default... 

> Changing this : importance_df['Feature'].str.len().max()
By this: max(importance_df['Feature'], key=len)
Should do the trick :) !

Ah, weird. Why would this make a difference? Anyway, will add it to the next release...

**Comment by amine-hef** [comment]
I opened an issue here: https://github.com/slundberg/shap/issues/2208
Thanks for your help.
