### ISSUE TITLE
joblib.dump(explainer,explainer_path) fails with KernelExplainer

### ISSUE THREAD

**Issue by tunayokumus** [oegedijk/explainerdashboard#129]
Hi Oege,

and thanks for this project. It's very helpful!

This applies to both joblib.dump and explainer.dump().
This happens only with self.shap=='kernel' Which provides the model_predict function to shap.KernelExplainer().

Here is the error:

`_pickle.PicklingError: Can't pickle <function BaseExplainer.shap_explainer.<locals>.model_predict at 0x00000228AA27AAF8>: it's not found as explainerdashboard.explainers.BaseExplainer.shap_explainer.<locals>.model_predict`

**Comment by tunayokumus** [comment]
Looks like this is related to how pickle works. 
Using "explainer.dill" instead of joblib & pickle works fine for Explainers with KernelExplainer (as it needs to pickle a local function)

**Comment by oegedijk** [comment]
Ah, interesting! So there indeed must be some unpicklable attribute inside the KernelExplainer

**Comment by oegedijk** [comment]
I can add a warning to the code when someone tries to pickle a KernelExplainer

**Comment by oegedijk** [comment]
added it! Will be in next release!
