### ISSUE TITLE
IDEA: ExplainerHub base_route to affect the base_url_path of the hub index

### ISSUE THREAD

**Issue by tunayokumus** [oegedijk/explainerdashboard#130]
Hi Oege,

I find the index page with the navbars you created very practical. However, it is not always suitable to have the hub directly routed to host:port and to host:port/index

What do you think about moving the ExplainerHub index and all the related flask routes to base_route (**host:port/base_route** and **host:port/base_route/index**). Without any additional redirects to host:port/ and to host:port/index. Would this be a breaking change in the way the ExplainerHub behaves?

I noticed that the individual Dashboards are already using the base_route in their base_url_path. But that the ExplainerHub has the index hard coded.
Also the routes for the hub frame seem to be hardcoded.

**Comment by tunayokumus** [comment]
If this would not be on focus atm, I can try creating a PR for this. Although I am not well versed with Flask

**Comment by oegedijk** [comment]
Ah, sure! Don't think it should be a breaking change as long as we keep the default behaviour in place!

**Comment by oegedijk** [comment]
merged the pr so closing...
