### ISSUE TITLE
Docker deployment example issue

### ISSUE THREAD

**Issue by DFoly** [oegedijk/explainerdashboard#132]
Hi Oege,

I am attempting to run the docker deployment example from [(https://explainerdashboard.readthedocs.io/en/latest/deployment.html)]

After running  docker run -p 9050:9050 explainerdashboard
I get a site cannot be reached an error.
Launching the app locally using the commands defined in the Dockerfile works fine.

**Comment by DFoly** [comment]
Problem solved.
The script opens http://172.17.0.2:9050 but the dashboard is actually on 0.0.0.0:9050

**Comment by oegedijk** [comment]
Ah yeah, the ip address displayed there is inside the docker container.
