### ISSUE TITLE
Routing issues when ExplainerHub is served with https instead of http

### ISSUE THREAD

**Issue by tunayokumus** [oegedijk/explainerdashboard#134]
The "Go to dashboard" links inside the iframe is not working when the hub is served with https.

Example:
ExplainerHub is served to : https://mydomain.com/projectpath/index 
ExplainerHub with bootstrap wrapper served at: https://mydomain.com/projectpath/hub
Dashboard1 is served to: https://mydomain.com/projectpath/dashboard1
Dashboard1 with bootstrap wrapper served at:  https://mydomain.com/projectpath/_dashboard1

All these links function by themselves when manually requested. Also the "Go to Dashboard" links are functioning from
https://mydomain.com/projectpath/index.

However, when the user clicks on the link "Go to Dashboard"(href: https://mydomain.com/projectpath/dashboard1) from https://mydomain.com/projectpath/hub (the route where the hub is served inside an iframe), then nothing happens.

The console gives the error:
Mixed Content: The page at 'https://mydomain.com/projectpath/hub/' was loaded over HTTPS, but requested an insecure resource 'http://mydomain.com/projectpath/dashboard1/'. This request has been blocked; the content must be served over HTTPS.

When I hover my cursor over the "Go to Dashboard" link it actually shows a https link. So I wasn't really able understand why this is happening.

**Comment by oegedijk** [comment]
Hi @tunayokumus,

Sorry for not getting back earlier. In any case I have no idea how to solve the issue :)

Did you manage to figure something out?

**Comment by oegedijk** [comment]
Hi @tunayokumus any progress? Shall I close this issue for now?

**Comment by tunayokumus** [comment]
Hi @oegedijk,

sorry I totally missed your response.
Unfortunately I couldn't find a fix for this. Right now, I disabled the bootstrap wrapper & iframe completely and only using the https://mydomain.com/projectpath/index to navigate to the index page. There I can navigate to individual dashboards, and have to use the "Previous page" function of the browser to navigate back. It is a bit tedious and we are losing some functionality this way. But I needed a quick fix back then.

I might go back and tackle this in the future, though for now I won't be focusing on this.
