### ISSUE TITLE
NameError: name 'ExplainerHub' is not defined

### ISSUE THREAD

**Issue by vinny2393** [oegedijk/explainerdashboard#138]
I have just created   single dashboard using Explainerdashboard  and its running good on random forest  and when i am trying to create ExplainerHub for multiple dashboard 
its shows up Name Error :: name 'ExplainerHub' is not defined
Please find the code below

from explainerdashboard import ClassifierExplainer, ExplainerDashboard

explainer_1 = ClassifierExplainer(clf_rf, X_train[test_asset], y_train[test_asset],
                               labels = ['Trade', 'No Trade'])

train = ExplainerDashboard(explainer_1, 
                      
                        
                        #importance tabs:
                        importance = True,
                        
                        hide_importance = True,
                        
                        #classification stats tabs:
                        
                        hide_globalcutoff=True, 
                        hide_modelsummary=True, 
                        hide_confusionmatrix=True,
                        hide_precision=True, 
                        hide_classification=True,
                        hide_rocauc=True, 
                        hide_prauc=True,
                        hide_liftcurve=True, 
                        hide_cumprecision=True,
                        
                        # Contribution
                        contribution = False,
                        
                        # regression stats tab:
                        #model_summary = True,
                        
                        #hide_modelsummary=True, 
                        hide_predsvsactual=True, 
                        hide_residuals=True, 
                        hide_regvscol=True,
                        
                        # individual predictions tab:
                        hide_predindexselector=True,
                        hide_predictionsummary=True,
                        hide_contributiongraph=True,
                        hide_pdp=True, 
                        hide_contributiontable=True,
                        
                        # whatif tab:
                        whatif = False,
                        
                        hide_whatifindexselector=True,
                        hide_whatifprediction=True,
                        hide_inputeditor=True, 
                        hide_whatifcontributiongraph=True, 
                        hide_whatifcontributiontable=True,
                        hide_whatifpdp=True,
                        
                        # shap dependence tab:
                        shap_dependence = False,
                        
                        hide_shapsummary=True, 
                        hide_shapdependence=True,
                        
                        # shap interactions tab:
                        shap_interaction=False,
                        
                        hide_interactionsummary=True,
                        hide_interactiondependence=True,
                        
                        # decisiontrees tab:
                        decision_trees = False,
                        
                        hide_treeindexselector=True,
                        hide_treesgraph=True, 
                        hide_treepathtable=True,
                        hide_treepathgraph=True,
                
                        ######################
                        mode='external')

explainer_2 = ClassifierExplainer(clf_rf, X_validate[test_asset], y_validate[test_asset],
                               labels = ['Trade', 'No Trade'],
                                 )

validate = ExplainerDashboard(explainer_2, 
                      
                        
                        #importance tabs:
                        importance = True,
                        
                        hide_importance = True,
                        
                        #classification stats tabs:
                        
                        hide_globalcutoff=True, 
                        hide_modelsummary=True, 
                        hide_confusionmatrix=True,
                        hide_precision=True, 
                        hide_classification=True,
                        hide_rocauc=True, 
                        hide_prauc=True,
                        hide_liftcurve=True, 
                        hide_cumprecision=True,
                        
                        # Contribution
                        contribution = False,
                        
                        # regression stats tab:
                        #model_summary = True,
                        
                        #hide_modelsummary=True, 
                        hide_predsvsactual=True, 
                        hide_residuals=True, 
                        hide_regvscol=True,
                        
                        # individual predictions tab:
                        hide_predindexselector=True,
                        hide_predictionsummary=True,
                        hide_contributiongraph=True,
                        hide_pdp=True, 
                        hide_contributiontable=True,
                        
                        # whatif tab:
                        whatif = False,
                        
                        hide_whatifindexselector=True,
                        hide_whatifprediction=True,
                        hide_inputeditor=True, 
                        hide_whatifcontributiongraph=True, 
                        hide_whatifcontributiontable=True,
                        hide_whatifpdp=True,
                        
                        # shap dependence tab:
                        shap_dependence = False,
                        
                        hide_shapsummary=True, 
                        hide_shapdependence=True,
                        
                        # shap interactions tab:
                        shap_interaction=False,
                        
                        hide_interactionsummary=True,
                        hide_interactiondependence=True,
                        
                        # decisiontrees tab:
                        decision_trees = False,
                        
                        hide_treeindexselector=True,
                        hide_treesgraph=True, 
                        hide_treepathtable=True,
                        hide_treepathgraph=True,
                
                        ######################
                        mode='external')

explainer_3 = ClassifierExplainer(clf_rf, X_oos[test_asset], y_oos[test_asset],
                               labels = ['Trade', 'No Trade'],
                                 )
oos = ExplainerDashboard(explainer_3, 
                     
                        #importance tabs:
                        importance = True,
                        
                        hide_importance = True,
                        
                        #classification stats tabs:
                        
                        hide_globalcutoff=True, 
                        hide_modelsummary=True, 
                        hide_confusionmatrix=True,
                        hide_precision=True, 
                        hide_classification=True,
                        hide_rocauc=True, 
                        hide_prauc=True,
                        hide_liftcurve=True, 
                        hide_cumprecision=True,
                        
                        # Contribution
                        contribution = False,
                        
                        # regression stats tab:
                        #model_summary = True,
                        
                        #hide_modelsummary=True, 
                        hide_predsvsactual=True, 
                        hide_residuals=True, 
                        hide_regvscol=True,
                        
                        # individual predictions tab:
                        hide_predindexselector=True,
                        hide_predictionsummary=True,
                        hide_contributiongraph=True,
                        hide_pdp=True, 
                        hide_contributiontable=True,
                        
                        # whatif tab:
                        whatif = False,
                        
                        hide_whatifindexselector=True,
                        hide_whatifprediction=True,
                        hide_inputeditor=True, 
                        hide_whatifcontributiongraph=True, 
                        hide_whatifcontributiontable=True,
                        hide_whatifpdp=True,
                        
                        # shap dependence tab:
                        shap_dependence = False,
                        
                        hide_shapsummary=True, 
                        hide_shapdependence=True,
                        
                        # shap interactions tab:
                        shap_interaction=False,
                        
                        hide_interactionsummary=True,
                        hide_interactiondependence=True,
                        
                        # decisiontrees tab:
                        decision_trees = False,
                        
                        hide_treeindexselector=True,
                        hide_treesgraph=True, 
                        hide_treepathtable=True,
                        hide_treepathgraph=True,
                
                        ######################
                        mode='external')

#explainer - Hub

hub = ExplainerHub([train, validate, oos])

hub.run(port=8050)

**Comment by oegedijk** [comment]
Hi, sorry for late reply, but did you include

```
from explainerdashboard import ExplainerHub
```

?

**Comment by vinny2393** [comment]
Hi Oegdijk 

It got resolved, There was a NumPy version issue in my anaconda, so I got an error.  I got a request, is there anyway, where Explainerhub can be saved into Html, which is much required for my project.

**Comment by oegedijk** [comment]
Right now, ExplainerHub cannot be exported to static html, only individual ExplainerDashboards.

Can look into it though, shouldn't be too hard to implement (I think :)
