### ISSUE TITLE
Exception: Model does not have a known objective or output type! When model_output is not "raw" then we need to know the model's objective or link function.

### ISSUE THREAD

**Issue by muhammad49** [oegedijk/explainerdashboard#139]
**I am trying to build a explainer dashboard with multiclass model but it is throwing the following error**
"
Exception                                 Traceback (most recent call last)
<ipython-input-105-d37d4aaf569b> in <module>
      8 
      9 from explainerdashboard import ClassifierExplainer, ExplainerDashboard, RegressionExplainer, ExplainerHub
---> 10 explainer = ClassifierExplainer(model, X_test, y_test)

~\Anaconda3\lib\site-packages\explainerdashboard\explainers.py in __init__(self, model, X, y, permutation_metric, shap, X_background, model_output, cats, cats_notencoded, idxs, index_name, target, descriptions, n_jobs, permutation_cv, cv, na_fill, precision, labels, pos_label)
   2039             self.__class__ = XGBClassifierExplainer
   2040 
-> 2041         _ = self.shap_explainer
   2042 
   2043 

~\Anaconda3\lib\site-packages\explainerdashboard\explainers.py in shap_explainer(self)
   2158                               "pass model_output='logodds' to get shap values in logodds without the need for "
   2159                               "a background dataset and also working shap interaction values...")
-> 2160                         self._shap_explainer = shap.TreeExplainer(
   2161                                                     self.model,
   2162                                                     self.X_background if self.X_background is not None else self.X,

~\Anaconda3\lib\site-packages\shap\explainers\_tree.py in __init__(self, model, data, model_output, feature_perturbation, feature_names, **deprecated_options)
    161         if self.model.model_output != "raw":
    162             if self.model.objective is None and self.model.tree_output is None:
--> 163                 raise Exception("Model does not have a known objective or output type! When model_output is " \
    164                                 "not \"raw\" then we need to know the model's objective or link function.")
    165 

Exception: Model does not have a known objective or output type! When model_output is not "raw" then we need to know the model's objective or link function.
"
**I am simply passing model and test (data+label) like 
explainer = ClassifierExplainer(model, X_test, y_test)
**

**Comment by oegedijk** [comment]
Hi,

Are you able to re-create this error with the titanic dataset? That would make it easier to debug:

```
from explainerdashboard import ClassifierExplainer, ExplainerDashboard
from explainerdashboard.datasets import titanic_survive


X_train, y_train, X_test, y_test = titanic_embarked()
model = # Your model definition here
model.fit(X_train, y_train)

explainer = ClassifierExplainer(model, X_test, y_test)
```

**Comment by muhammad49** [comment]
I have uploaded the dataset and my python code for you to re-create that error
[titanicTrain.zip](https://github.com/oegedijk/explainerdashboard/files/6974020/titanicTrain.zip)

**Comment by oegedijk** [comment]
Hi, 

So it seems that multiclass xgboost classifiers don't work nice with probability outputs. So a quick fix is simply passing

```python
explainer = ClassifierExplainer(model, X_test, y_test, model_output='logodds')
```
Will see if I can make this the default behaviour.

**Comment by oegedijk** [comment]
Okay, that was an easy fix. Will be in next release.
