### ISSUE TITLE
Tabs are freezing

### ISSUE THREAD

**Issue by nailcankara** [oegedijk/explainerdashboard#140]
I have dataset which has 100k row and 50 column. I use classification use case. 
--
Feature Importances
Classification Stats
--
tabs are opened in ~1sec.

---
Individual Predictions
What if...
Feature Dependence
Decision Trees
---
This tabs are opend in 30 second... What is the problem? I think they are precomputed values aren't they?

**Comment by oegedijk** [comment]
The feature dependence being slow could be due to plotting too many points in the graph, could you try passing a parameter `plot_sample=1000` to the dashboard?

The other tabs are a bit more murky why they would be slow, but maybe they are just waiting for the feature dependence page to render?

**Comment by oegedijk** [comment]
Did you try the plot_sample trick? Did it work?
