### ISSUE TITLE
Group cats option and issue with confusion matrix

### ISSUE THREAD

**Issue by akocienia** [oegedijk/explainerdashboard#141]
Hi! 

First of all, I truly LOVE your work and I think it's awesome to have such a reusable dashboard to easily analyze the results of practically any machine learning model. Thank you for that! 

While exploring the options, I've noticed two issues with my classification dashboards. First one is the lack of the _Group cats_ option which is visible on your demonstration gif: 

![image](https://user-images.githubusercontent.com/40331773/128874513-70219bcc-5890-4cf5-be30-740863e18d0a.png)

I also noticed that this option is not visible on your example of the dashboard as well: http://titanicexplainer.herokuapp.com/classifier/ 

Is it something that could be fixed? I'd really appreciate this option! 

The other issue is with confusion matrix for multiclass classification. I've noticed that when you use the option Display one-vs-rest matrix the numbers are different compared to the case when I don't use this option. Example from your Multiclass Explainer: 

![image](https://user-images.githubusercontent.com/40331773/128875120-6645c7ec-29bc-460b-9ba6-c928320e7936.png)

There are 140 Southampton classified correctly as Southampton...

![image](https://user-images.githubusercontent.com/40331773/128875241-48b3c5d4-5db8-4742-8a25-ecafb939dbfe.png)

While with the "full" confusion matrix there are 142. In my dashboards, those differences could be sometimes much higher and lead to misleading results. Why is it happening? 

Thanks in advance! 😃

**Comment by oegedijk** [comment]
Hi,

The first issue is simply the gif being out of date: I now just group the
onehot encoded features by default. Before I was storing both the grouped
and the ungrouped shap values, and this created quite some overhead (both
storage and complexity). At some point I added a feature that made this
even more cumbersome so I decided to simplify it. Still need to
rerecord the gif though!

The confusion matrix issue is a bit weird (and worrying) though! Will look
into it! (currently at home with a newborn, so don't have a ton of time,
but will try to make some).

Thanks for using the dashboard and giving your feedback!

**Comment by oegedijk** [comment]
I think I have an idea where this comes from.

For the binary confusion matrix I calculate 

```python
confusion_matrix(np.where(y==pos_label, 1, 0), 
                                        np.where(pred_probas[:, pos_label] >= cutoff, 1, 0))
```

for the multiclass confusion matrix I calculate

```python
confusion_matrix(self.y, self.pred_probas_raw.argmax(axis=1))
```

So in the binary case, there are 140 cases where P(Southampton) > 0.5, but in the multi class case there are 142 cases where P(Southampton) is larger than both P(Queenstown) and P(Cherbourg) (or the first in the array in case of tie). So for example [[0.3, 0.4, 0.3]] would count as Southampton in the multi class case, but as Not Southhampton in the binary case.

So I think this behaviour makes sense?

**Comment by akocienia** [comment]
Hi, 

Thank you for explaining! 

When it comes to the confusion matrix I suppose it makes sense - it can be even used to check how certain the model is while exploring multi-class classification. By manipulating the global cut-off it's possible to check how much of data is classified to the given class although it was below certain level of probability. That could be very helpful! 

When it comes to the grouping/ungrouping the one-hot-encoded features I would like to still use this option to have a chance to validate the importance of the individual values of the feature as well. Could you please let me know in which version this option is still available so I could check it out?

Thanks!

**Comment by oegedijk** [comment]
You can try the last version before version 0.3: https://github.com/oegedijk/explainerdashboard/releases/tag/v0.2.20.1
