### ISSUE TITLE
Specfying pickling method in the arguments of hub.to_yaml()

### ISSUE THREAD

**Issue by tunayokumus** [oegedijk/explainerdashboard#146]
As stated in [this issue](https://github.com/oegedijk/explainerdashboard/issues/129), pickle or joblib dumping is problematic with KernelExplainer. However, hub.to_yaml uses only joblib format and does not accept an argument for it and therefore fails for kernelexplainer.

Also not specifying a filepath in this method is giving an error instead of returning the yaml config. 

I can submit a PR addressing these sometime soon.

**Comment by oegedijk** [comment]
Hi @tunayokumus,

Sorry for not getting back earlier. You are right, the dashboards get dumped to `.joblib` by default. Should be straightforward to add multiple options here. But would be happy to accept a PR!

**Comment by oegedijk** [comment]
Okay, added it. Will be in the next release as an extra parameter `pickle_type` that default to `"joblib"`, but can also be set `"dill" or `"pkl"`...
