### ISSUE TITLE
Use IndexConnector with external index to update ShapContributionsGraphComponent

### ISSUE THREAD

**Issue by jeanhofer** [oegedijk/explainerdashboard#149]
I would like to implement an app in Dash with an interactive DashDataTable and a ShapContributionsGraphComponent which is updated based on the selected row of the DataTable. Each row of the table corresponds to a prediction that can be analyzed with a ShapContributionsGraph. 

Is it possible to update the ShapContributionsGraph based on the selected index of the DataTable? I thought it may be possible to use IndexConnector with the selected index as an input argument. The documentation of IndexConnector says:  

>Args: input_index ([{str, ExplainerComponent}]): Either a str or an ExplainerComponent. If str should be equal to the
name of the index property. If ExplainerComponent then should have a .index_name property.

However if I use an index as str input, e.g.
`IndexConnector('Palsson, Master. Gosta Leonard', self.contributions)`

there is an error in validate_callback_arg(arg):
`IncorrectTypeException: component_id must be a string or dict, found ['P', 'a', 'l', 's', 's', 'o', 'n', ',', ' ', 'M', 'a', 's', 't', 'e', 'r', '.', ' ', 'G', 'o', 's', 't', 'a', ' ', 'L', 'e', 'o', 'n', 'a', 'r', 'd']`

What would be the correct format of the input argument to IndexConnector? Is there a better way to achieve the described goal?

**Comment by oegedijk** [comment]
Hi @jeanhofer,

The IndexConnector is meant to connect the index selection dropdown menu between two explaincomponents. So the first argument.

So the first argument should be the dash id of the index dropdown, e.g. `IndexConnector('custom-index-dropdown-id', self.contributions)`...

Or if the first argument is an `ExplainerComponent` that has an `.index_name` property it uses that.

```python
class IndexConnector(ExplainerComponent):
    def __init__(self, input_index, output_indexes, explainer=None):
        """Connect the index selector of input_index with those of output_indexes.

        You can use this to connect a RandomIndexComponent with a
        PredictionSummaryComponent for example.

        When you change the index in input_index, all the indexes in output_indexes
        will automatically be updated.

        Args:
            input_index ([{str, ExplainerComponent}]): Either a str or an
                        ExplainerComponent. If str should be equal to the
                        name of the index property. If ExplainerComponent then
                        should have a .index_name property.
            output_indexes (list(str, ExplainerComponent)): list of str of
                        ExplainerComponents.
        """
        self.input_index_name = self.index_name(input_index)
        self.output_index_names = self.index_name(output_indexes)
        self.explainer = explainer
        if not isinstance(self.output_index_names, list):
            self.output_index_names = [self.output_index_names]

    @staticmethod
    def index_name(indexes):#, multi=False):
        def get_index_name(o):
            if isinstance(o, str): return o
            elif isinstance(o, ExplainerComponent):
                if not hasattr(o, "index_name"):
                    raise ValueError(f"{o} does not have an .index_name property!")
                return o.index_name
            raise ValueError(f"{o} is neither str nor an ExplainerComponent with an .index_name property")

        if hasattr(indexes, '__iter__'):
            index_name_list = []
            for index in indexes:
                index_name_list.append(get_index_name(index))
            return index_name_list
        else:
            return get_index_name(indexes)

    def component_callbacks(self, app):
        @app.callback(
            [Output(index_name, 'value') for index_name in self.output_index_names],
            [Input(self.input_index_name, 'value')]
        )
        def update_indexes(index):
            if self.explainer is not None:
                if self.explainer.index_exists(index):
                    return tuple(index for i in range(len(self.output_index_names)))
                else:
                    raise PreventUpdate
            return tuple(index for i in range(len(self.output_index_names)))
```
