### ISSUE TITLE
Feature request: Decision Trees tab: adjust location of labels for decision trees

### ISSUE THREAD

**Issue by raybellwaves** [oegedijk/explainerdashboard#15]
Again, loving this package.

Using 

```
explainer = RegressionExplainer(model, X_test, y_test, cats=cats, shap="tree")
ExplainerDashboard(explainer).run()
```

There are a couple of instances where the y label is on top of the avg pred label (see below) on the decision trees tab. Would be good if somehow they could be slightly separated. In addition, perhaps y could be renamed to a friendlier common term 'observed'?

![image](https://user-images.githubusercontent.com/17162724/99019414-3e5bf480-252a-11eb-95cf-e79673c47919.png)

**Comment by oegedijk** [comment]
Ah, yeah, will have a look at how I can get a cleaner separation in plotly figs. Also thinking of maybe adding some bars to the right for average prediction and observed.

It was first called "actual", then I named it "y", but I agree that "observed" is probably the right name. 

In general though: if the average prediction and observed are so close that they become hard to distinguish in the plot, that does kind of communicate the point, no? :)

**Comment by oegedijk** [comment]
Will be fixed in the next release!
