### ISSUE TITLE
Rule based explanations?

### ISSUE THREAD

**Issue by rezacsedu** [oegedijk/explainerdashboard#151]
Is there a plan to add rule-based explanation functionality? Sometimes, providing local or individual explanations in terms of rules is beneficial as rules are very intuitively simple to explain model decisions even to a non-domain expert. (don't know but seems rules can be extracted even from the decision path table).

**Comment by oegedijk** [comment]
Hi @rezacsedu,

I have currently no plans for this, but if you have an easy implementable method for this I could look into it!
