### ISSUE TITLE
Import error of explainerdashboard library on databricks.

### ISSUE THREAD

**Issue by muhammad49** [oegedijk/explainerdashboard#156]
I am simply importing the explainerdashboard like this
`
from explainerdashboard import ClassifierExplainer, ExplainerDashboard, RegressionExplainer, ExplainerHub

`
and it is throwing this error

> 
ImportError                               Traceback (most recent call last)
<command-742270636411273> in <module>
----> 1 from explainerdashboard import ClassifierExplainer, ExplainerDashboard, RegressionExplainer, ExplainerHub

/databricks/python/lib/python3.7/site-packages/explainerdashboard/__init__.py in <module>
----> 1 from .explainers import ClassifierExplainer, RegressionExplainer
      2 from .dashboards import ExplainerDashboard, ExplainerHub, InlineExplainer

/databricks/python/lib/python3.7/site-packages/explainerdashboard/explainers.py in <module>
     25 import shap
     26 
---> 27 from dtreeviz.trees import ShadowDecTree, dtreeviz
     28 
     29 from sklearn.model_selection import KFold

/databricks/python/lib/python3.7/site-packages/dtreeviz/__init__.py in <module>
      1 from .version import __version__
      2 
----> 3 from dtreeviz.classifiers import clfviz

/databricks/python/lib/python3.7/site-packages/dtreeviz/classifiers.py in <module>
      9 
     10 from dtreeviz.colors import adjust_colors, GREY
---> 11 from dtreeviz.trees import add_classifier_legend
     12 from dtreeviz import utils
     13 

/databricks/python/lib/python3.7/site-packages/dtreeviz/trees.py in <module>
     11 import matplotlib.pyplot as plt
     12 from colour import Color, rgb2hex
---> 13 from graphviz.backend import run, view
     14 from sklearn import tree
     15 from typing import Mapping, List, Tuple

ImportError: cannot import name 'run' from 'graphviz.backend' (/databricks/python/lib/python3.7/site-packages/graphviz/backend/__init__.py)

**Comment by oegedijk** [comment]
Hi, that seems to be an issue with the dtreeviz library, that explainerdashboard uses to visualize decision trees. 

Does it also crash when you simply only import `dtreeviz`?

If so, I would take it up with the dtreeviz library maintainers: https://github.com/parrt/dtreeviz

(don't work with databricks myself, so not so easy for me to debug...)

**Comment by thvasilo** [comment]
In my case I had installed `explainerdashboard` through conda-forge, and it turns out I had to install graphviz separately using `conda install python-graphviz`.

**Comment by oegedijk** [comment]
@thvasilo that's interesting, as `dtreeviz` actually tells you to install `python-graphviz` on conda: https://github.com/parrt/dtreeviz#install

graphviz on conda is a bit of a mess.

**Comment by DannyDannyDanny** [comment]
I am simply importing the explainerdashboard like this
`from explainerdashboard import ClassifierExplainer, ExplainerDashboard, RegressionExplainer, ExplainerHub`
and it is throwing this error
```
ImportError Traceback (most recent call last)
in
----> 1 from explainerdashboard import ClassifierExplainer, ExplainerDashboard, RegressionExplainer, ExplainerHub

/databricks/python/lib/python3.7/site-packages/explainerdashboard/init.py in
----> 1 from .explainers import ClassifierExplainer, RegressionExplainer
2 from .dashboards import ExplainerDashboard, ExplainerHub, InlineExplainer

/databricks/python/lib/python3.7/site-packages/explainerdashboard/explainers.py in
25 import shap
26
---> 27 from dtreeviz.trees import ShadowDecTree, dtreeviz
28
29 from sklearn.model_selection import KFold

/databricks/python/lib/python3.7/site-packages/dtreeviz/init.py in
1 from .version import version
2
----> 3 from dtreeviz.classifiers import clfviz

/databricks/python/lib/python3.7/site-packages/dtreeviz/classifiers.py in
9
10 from dtreeviz.colors import adjust_colors, GREY
---> 11 from dtreeviz.trees import add_classifier_legend
12 from dtreeviz import utils
13

/databricks/python/lib/python3.7/site-packages/dtreeviz/trees.py in
11 import matplotlib.pyplot as plt
12 from colour import Color, rgb2hex
---> 13 from graphviz.backend import run, view
14 from sklearn import tree
15 from typing import Mapping, List, Tuple

ImportError: cannot import name 'run' from 'graphviz.backend' (/databricks/python/lib/python3.7/site-packages/graphviz/backend/init.py)
```
