### ISSUE TITLE
Use Download component from dash-extensions

### ISSUE THREAD

**Issue by m-braverman** [oegedijk/explainerdashboard#158]
I got an error about dcc.Download, and changed the import to be from dash-extensions. 
I'm using the latest dash.

dash==2.0.0
dash-auth==1.4.1
dash-bootstrap-components==0.13.1
dash-core-components==2.0.0
dash-daq==0.1.7
dash-extensions==0.0.65
dash-html-components==2.0.0
dash-renderer==1.0.0
dash-table==5.0.0
explainerdashboard==0.3.7
jupyter-dash==0.4.0

I suggest changing dashboards.py file to import the Download component from dash-extensions.

**Comment by oegedijk** [comment]
Hi @m-braverman, could you detail the error? Show an example where it fails?

The download component originated in dash-extensions, but was then integrated into the main library. 

I would prefer not to add another dependency if possible...

**Comment by m-braverman** [comment]
I tried replicating this with a new venv, but couldn't. 
The error was "Module ‘dash_core_components’ has no attribute ‘Download’".
Closing this.
