### ISSUE TITLE
using explainerdashboard with H2OAutoMLClassifier

### ISSUE THREAD

**Issue by luchpa** [oegedijk/explainerdashboard#160]
Hi!
Thanks for making the explainerdashboard, it seems to be a great tool for data scientists!

I have a question: Is it possible to run ClassifierExplainer on H2O models, such as H2OAutoMLClassifier? It seems to be a sklearn wrapper for the H2OAutoML module.
(https://github.com/h2oai/h2o-tutorials/blob/master/tutorials/sklearn-integration/H2OAutoML_as_sklearn_estimator.ipynb)

Thanks in advance!

**Comment by oegedijk** [comment]
Hi @luchpa, then it should in principle be compatible, as long as it works with `shap`. However there are multiple `shap` algorithms for different types of models (`TreeExplainer`, `LinearExplainer`), so with a AutoML algorithms I could imagine that it may be hard to find the right working shap explainer. 

Could you try if you get the shap library to work with `H2OAutoMLClassifier`?

**Comment by oegedijk** [comment]
Hi @luchpa, were you able to generate shap values for `H2OAutoMLClassifier` yourself?

**Comment by maaz19499** [comment]
Hi @oegedijk , Explainer Dashboard is a much needed tool for data scientist and thank you so much for creating it.

I had a question that is there any way to integrate h2o's driverless ai  mli data into explainer dashboard to create the beautiful dashboard?
(https://docs.h2o.ai/driverless-ai/latest-stable/docs/userguide/interpret-a-model.html)

Thank you in advance.

**Comment by oegedijk** [comment]
Hi @maaz19499 it seems that `h2o` is using shapley values as well for some of those analysis. So h20 has already calculated those, then you don't need to calculate them separately inside the `explainer`, but can pass them with the `explainer.set_shap_values(...)` method...
