### ISSUE TITLE
TypeError: can only concatenate str (not "int") to str

### ISSUE THREAD

**Issue by andrecasotti** [oegedijk/explainerdashboard#162]
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train_norm, y_train)

explainer = ClassifierExplainer(model, X_test_norm, y_test,
                                    shap='linear',
                                    X_background=X_train,
                                    model_output='logodds',labels=['0', '1'])
ExplainerDashboard(explainer).run()

And i'm getting this error:
TypeError: can only concatenate str (not "int") to str

**Comment by oegedijk** [comment]
Hi @andrecasotti, could you post a longer stack trace?

From this I cannot see something obviously wrong, but I'm guessing it's probably something non-standard in your dataframes?
