### ISSUE TITLE
Unable to use SimplifiedClassifierDashboard

### ISSUE THREAD

**Issue by oluwole-rewire** [oegedijk/explainerdashboard#168]
![image](https://user-images.githubusercontent.com/93487689/147890272-7707cc0a-a93b-4abb-bc1b-f188729bc5f7.png)
I tried to pip install explainerdashboard again but to no avail.

**Comment by oegedijk** [comment]
Hi @oluwole-rewire,

the composite is called `SimplifiedClassifierComposite` not `SimplifiedClassifierDashboard`:

https://github.com/oegedijk/explainerdashboard/blob/bdd03da0edd6efb48876e539bc0669101c6bb990/explainerdashboard/dashboard_components/composites.py#L684

So this should work:

```python
from explainerdashboard.custom import SimplifiedClassifierComposite, ImportancesComposite


explainer = ...
ExplainerDashboard(explainer, [ImportancesComposite, SimplifiedClassifierComposite]).run()
```
