### ISSUE TITLE
add link to docs at top of github repo

### ISSUE THREAD

**Issue by raybellwaves** [oegedijk/explainerdashboard#17]
You can add a link to documentation in the top right of the github page - under About

https://explainerdashboard.readthedocs.io/en/latest/

![Screenshot from 2020-11-17 09-26-33](https://user-images.githubusercontent.com/17162724/99402301-321fc080-28b7-11eb-878d-6d6d175911df.png)

**Comment by oegedijk** [comment]
Done!
