### ISSUE TITLE
Support for Lime explainer

### ISSUE THREAD

**Issue by SSMK-wq** [oegedijk/explainerdashboard#172]
Hello, 

I am new to data science and came across this package and found it extremely useful for people like me who don't know web-app development. Great work. I can't thank you enough. I have a quick question.

I am learning explainable AI and came to know that we have SHAP, LIME, PFI etc.

I see in docs that we have SHAP and PFI explainer but does the package support Lime explainer as well?

I couldn't find out. Hence, thought of checking with you

Can help me please

**Comment by oegedijk** [comment]
Hi @SSMK-wq,

I'm personally not a huge fan of LIME: you are approximating the real model with a local simple model within a certain kernel, but is heavily dependent on the kernel size and other assumption what you get out of it. 

Having said that the shap library has a wrapper for lime that I could use: https://shap.readthedocs.io/en/latest/generated/shap.explainers.other.LimeTabular.html

so worth thinking about implementing that one...
