### ISSUE TITLE
Bug in dahsboard when the columns has especial characters

### ISSUE THREAD

**Issue by reza1615** [oegedijk/explainerdashboard#173]
It seems before sending feature columns to the explainerdashboard. it should have an option to force cleaning them automatically

InvalidComponentIdError: The element `feature-input-CE_Send to Fraud_1.0-input-40` contains `.` in its ID.
Characters `.`, `{` are not allowed in IDs

**Comment by oegedijk** [comment]
Hi @reza1615 that probably has something to do with the `orjson` encoder that encodes the dataframe to json before sending it to the browser. This is faster than the default python implementation but it seems it doesn't always play nice with special characters. It is entirely optional though so `pip uninstall orjson` should probably take care of the problem?
