### ISSUE TITLE
Filter out indexes by prediction score in "what if"

### ISSUE THREAD

**Issue by reza1615** [oegedijk/explainerdashboard#174]
It would be nice to have an option that we can just see the case that the predicted value is 1. For cases in which data is skew finding prediction ==1 is difficult.
for example in the below screenshot. select index just show label==1
![image](https://user-images.githubusercontent.com/2202483/149805294-71a0f70e-c726-4c25-b411-30547803ee29.png)

**Comment by oegedijk** [comment]
Euhm, @reza1615 not sure what you mean? do you mean the prediction==1 or the observed label==1? For the later case you can use the Observed Patricia_target selector and only select "1". For the first you could simply set the predicted probability range lower bound to e.g. 0.99?
