### ISSUE TITLE
Unable to use ordinal encoded data and model from Tpot

### ISSUE THREAD

**Issue by SSMK-wq** [oegedijk/explainerdashboard#177]
Hi,

I am using the model pipeline generated based on Tpot (Auto-ML solution) exhaustive search.

My code looks like as below

```
exported_pipeline = make_pipeline(
    StackingEstimator(estimator=LogisticRegression(C=0.01, dual=False, penalty="l2")),
    LogisticRegression(C=1.0, dual=False, penalty="l2")
)
exported_pipeline.fit(ord_train_t, y_train) #both train and test are ordinal encoded.
y_pred = exported_pipeline.predict(ord_test_t)
```

Later, I try to use the below from your documentation

`explainer = ClassifierExplainer(exported_pipeline,ord_test_t, y_test)`

Unfortunately, I get an error like as shown below

**ValueError: not enough values to unpack (expected 2, got 0)**

How can I avoid this error and use explainer dashboard to view my model explanation?

Can you help me please?

**Comment by oegedijk** [comment]
Hi,

The support for pipelines is right now very limited. Could you provide a longer stacktrace though to make it easier to see where that error came from?
