### ISSUE TITLE
update conda-forge

### ISSUE THREAD

**Issue by tvdboom** [oegedijk/explainerdashboard#181]
The [conda-forge](https://anaconda.org/conda-forge/explainerdashboard) version of the package is 0.3.6.2 (2 versions behind pypi). Is it possible to update the version on conda? Thanks in advance.

**Comment by tvdboom** [comment]
I'll give it a try: [https://github.com/conda-forge/explainerdashboard-feedstock/pull/37](https://github.com/conda-forge/explainerdashboard-feedstock/pull/37)

**Comment by oegedijk** [comment]
wow, awesome! Thanks so much!
