### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by yanivwisney** [oegedijk/explainerdashboard#182]
Hey!
When running the very first import line:
`from explainerdashboard import ClassifierExplainer, RegressionExplainer`
on jupyter notebook, I am running into this following import error:
`ImportError: cannot import name 'Input' from 'dash'`

Is it me or the code?

Thanks in advanced :)

**Comment by oegedijk** [comment]
Hi @yanivwisney,

That means that you still have dash 1.0 installed, you can upgrade to dash 2.0 with `pip install -U dash`. 

The dash version should have been bumped automatically with the latest release though given the requirements in `setup.py`: https://github.com/oegedijk/explainerdashboard/blob/f38b70f6d393abc511983a9b896da86097ab7b5f/setup.py#L71

Hmm

**Comment by yanivwisney** [comment]
Hey,
I double checked and re-installed dash of it's newest version - 2.1.0
and I'm still getting the same issue.

**Comment by oegedijk** [comment]
ah, weird. And if you try directly in your notebook:

```python
from dash import Input
```

?

**Comment by oegedijk** [comment]
for context: dash 2.0 made some changed to how you import various parts of the library: 

https://dash.plotly.com/dash-2-0-migration

**Comment by yanivwisney** [comment]
Actually when doing so, `from dash import Input` I am getting the same error.
I created an issue in the Dash's python forum.

**Comment by oegedijk** [comment]
okay, then I'm closing this for now!
