### ISSUE TITLE
Bug in PDP plot

### ISSUE THREAD

**Issue by baptiste-pasquier** [oegedijk/explainerdashboard#184]
https://github.com/oegedijk/explainerdashboard/blob/f38b70f6d393abc511983a9b896da86097ab7b5f/explainerdashboard/explainers.py#L1446

The `numpy.ndarray.sort` function sorts an array in-place and returns `None`.

A possible fix would be to use the `numpy.sort` function instead : 

```{python}
grid_values = np.sort(np.append(grid_values, val))
```

**Comment by oegedijk** [comment]
Ah, good catch! 

Will fix it in the next release!

**Comment by oegedijk** [comment]
just did the release!
