### ISSUE TITLE
How to save figures in high resolution in dashboard? thanks

### ISSUE THREAD

**Issue by Jie-NB** [oegedijk/explainerdashboard#187]

**Comment by oegedijk** [comment]
Does the save png button (
![image](https://user-images.githubusercontent.com/27999937/156149514-f5a46d35-de63-45e8-a0b4-0dd625e284b0.png)
) in the top right corner not provide sufficient high resolution image?

![image](https://user-images.githubusercontent.com/27999937/156149447-05cf121a-9ebb-4688-b28e-88c48c0e6815.png)
