### ISSUE TITLE
Citation?

### ISSUE THREAD

**Issue by e5k** [oegedijk/explainerdashboard#189]
Hi - Is there any way you'd like the code to be cited in publications?

**Comment by oegedijk** [comment]
Hi @e5k,

Haven't really thought about this :) How do packages usually get cited?

**Comment by e5k** [comment]
As such? 
https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content

You are now thoroughly acknowledged in a research paper, but happy to switch that to a proper citation if interested!

**Comment by oegedijk** [comment]
Ah, cool, switched on the zenodo thing. So should be a proper doi with the next release!

Do you have any link to a draft of the paper in question? 

Cheers!

**Comment by e5k** [comment]
Cool! I will submit it by the end of the week, but if you drop me a message at seb –at– eskd –dot– net I'll send you a link do my drive

**Comment by carolpiazzi** [comment]
Hi, I'm interested in citing your library. When you get the DOI of it, can you send it here in this thread please?

**Comment by oegedijk** [comment]
Hi @carolpiazzi, seems like zenodo provides a doi: https://zenodo.org/record/6408776
