### ISSUE TITLE
What about the deep learning models?

### ISSUE THREAD

**Issue by deekshith39** [oegedijk/explainerdashboard#190]

**Comment by oegedijk** [comment]
Hi @deekshith39,

The dashboard only supports model for tabular data that  sklearn-compatible (i.e. they are expected to have a `.fit()` and `.predict()` method, etc). That makes it possible to support a large variety of models through duck typing. 

Tabular deep learning PyTorch models are supported if they are wrapper with the skorch library: https://github.com/skorch-dev/skorch

I'm considering future support for tensorflow/keras wrappers, e.g. https://github.com/adriangb/scikeras

**Comment by anupam2505** [comment]
@oegedijk - I am planning to use the explainer dashboard for tensorlfow/keras models. Do we have an eta for tensorlfow/keras model support ? Thanks for this awesome tool.

**Comment by oegedijk** [comment]
Hi @anupam2505, currently I have very little time for developing new features for this project. However if you can make a start with preparing a demo of how to work with scikeras, pass in dataframes and get out shap values, then I can see if I can add the functionality to the dashboard!

**Comment by anupam2505** [comment]
@oegedijk - Sure ! Let me check more details about the scikeras. BTW Does explainerdashboard support PyTorch models which are are having different type of input like embeddings and numerical features ?
