### ISSUE TITLE
`dot` not recognised by check for executable

### ISSUE THREAD

**Issue by achimgaedke** [oegedijk/explainerdashboard#191]
Though I installed graphviz, I always get `WARNING: you don't seem to have graphviz in your path (cannot run 'dot -V') [...]`.

Looking at the code:
```
 stdout, stderr = be.run(cmd, capture_output=True, check=True, quiet=True)
```
always fails.

I adjusted this test to the module structure of the `backend`, which changed with https://github.com/xflr6/graphviz/releases/tag/0.18.2

**Comment by oegedijk** [comment]
ah, good catch and thanks for the PR!

graphviz dependency is quite a headache in general, but `dtreeviz` is also really cool so worth keeping it in :)
