### ISSUE TITLE
Incorporate scaling models to inverse X_test or y_test

### ISSUE THREAD

**Issue by firobeid** [oegedijk/explainerdashboard#197]
How can we incorporate the scaling function that we used to scale our inputs (X_train) into the dashboard so that in the whatif analysis for example, users raw input gets scaled before fed in the model?

**Comment by oegedijk** [comment]
Hi @firobeid,

That's a good question. Should in principle be possible I guess. So user could provide for example a dictionary with an encoder function and decoder function, e.g. `encoder_functions = {'Age': {'encoder': age_encoder, 'decoder': age_decoder}}`, and if these are passed then the dashboard could run input through these functions.

So should in theory be possible. Not sure I have the time right now to implement it though. Feel free to take a stab at it though!
