### ISSUE TITLE
How to check for __version__ ?

### ISSUE THREAD

**Issue by ttpro1995** [oegedijk/explainerdashboard#199]
```
import explainerdashboard
explainerdashboard.__version__
```

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-6024dcbde7b3> in <module>
----> 1 explainerdashboard.__version__

AttributeError: module 'explainerdashboard' has no attribute '__version__'
```

It should work. Most open-source does have variable __version__.  

For example: case of Numpy

```
import numpy
numpy.__version__

```
'1.19.2'

**Comment by oegedijk** [comment]
Hi @ttpro1995, I thought about adding this, but I'd like to have the version recorded in only one location, so wasn't sure how to make sure the same version ends up in `__version__` and in `setup.py`. 

Seems there should be some solutions for this though: https://stackoverflow.com/questions/458550/standard-way-to-embed-version-into-python-package

will see if I can implement it...

**Comment by oegedijk** [comment]
Added it to the latest release (0.3.8.1),  will see if in the future I can automatically link it to the version in setup.py because I'm sure I will forget to sync them at some point. (maybe can also just add a test in the github ci/cd)
