### ISSUE TITLE
how to deploy explainerdashboard in Rshiny app?

### ISSUE THREAD

**Issue by XinQi7788** [oegedijk/explainerdashboard#200]
Does anyone know how to deploy explainerdashboard as a Rshiny app?

Inside the Rstudio, we can use reticulate package to talk with the explainerdashboard written in python scripts. 
But don't know how to deploy it as a Rshiny app?

Thank you very much.

Xin

**Comment by oegedijk** [comment]
Hi @XinQi7788, I have no idea myself (not an R user anymore), but would be cool if there is a way to make it work!
