### ISSUE TITLE
deployment issue: could not find tbtools.py

### ISSUE THREAD

**Issue by XinQi7788** [oegedijk/explainerdashboard#201]
Hi

With following the instructions of deployment using gunicorn on localhost ($_gunicorn dashboard:app_), but encountered ImportError that could not import name as shown below.

ImportError: cannot import name 'get_current_traceback' from 'werkzeug.debug.tbtools' (/home/ubuntu/anaconda3/envs/dash/lib/python3.10/site-packages/werkzeug/debug/tbtools.py)

Please help on how to resolve the issue? Thank you very much.

Xin

**Comment by oegedijk** [comment]
yeah, this is an issue that has to do with a new version of werkzeug that got released a few days ago. You can fix it by installing the previous version: `pip install Werkzeug<=2.0.3`

I'm working on releasing a fix this evening, but the github CI/CD is broken for some reason...

**Comment by XinQi7788** [comment]
Thanks for a quick reply!

I changed to the previous version: pip install Werkzeug<=2.0.3 inside the requirements.txt, but after push to heroku master branch, got the following error message: 

heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/" host=ed-test-app.herokuapp.com request_id=a27c1a8f-f92f-4aff-afed-81eb74510167 fwd="34.202.79.235" dyno=web.1 connect=0ms service=30000ms status=503 bytes=0 protocol=https

heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/favicon.ico" host=ed-test-app.herokuapp.com request_id=b6fbd9e3-ca44-4a70-9b95-219649d9da74 fwd="34.202.79.235" dyno=web.1 connect=0ms service=30000ms status=503 bytes=0 protocol=https

Looking forward to your reply and thank you very much.
Xin

**Comment by oegedijk** [comment]
just released v0.3.8.1 that should fix the previous issue.

As for this latest one, I'm not sure... seems that the server is taking longer than 30 seconds to respond. Did you pre-calulcate all the shap values etc, and save the explainer to .joblib before loading it again in the heroku deployment?

**Comment by XinQi7788** [comment]
Thanks for such a quick reply! 

I did use yaml file to load the ExplainerDashboard. Here I attached the scripts I used to try to deploy in Heroku using Dash. Can you please let me know what is wrong with the dashboard.py or other files? Thank you very much. Looking forward to your reply!

Best Regards
Xin

[ED_test.zip](https://github.com/oegedijk/explainerdashboard/files/8401583/ED_test.zip)

**Comment by eakande** [comment]
I use this in my requirement.txt file and it works. In addition, I will advise you to create and run it in a virtual environment. You also do not seem to have the runtime.txt, this is explicitly stated in the document.  The runtime contains the version of your python e.g.    python-3.9.7

Moreover, what you posted is just an error code description which I am very familiar with, I will advise you to scroll up the Heroku error log details to find the exact cause of the code, just scroll up I am sure you will find it.

dash>=2
dash-bootstrap-components
dash-auth
explainerdashboard
gunicorn==20.1.0
jupyter_dash
dtreeviz>=1.1.4
numpy
pandas>=1.4.0
scikit-learn
openpyxl
shap>=0.37
joblib
oyaml
click
waitress
flask_simplelogin

Try this out......

**Comment by XinQi7788** [comment]
Hi eakande: thank you so much for your help!

Inside the virtual environment, runtime.txt file is added, and instead of using Dash, I changed to Flask inside the dashboard.py. After deployment on Heruko, still got error messages as below. I attached the scripts in the zipped file as well. Looking forward to your reply and thank you very much!

2022-04-04T14:06:44.800938+00:00 app[web.1]:     stack[-1] = func(*args)
2022-04-04T14:06:44.800938+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/numba/core/serialize.py", line 97, in _unpickle__CustomPickled
2022-04-04T14:06:44.800939+00:00 app[web.1]:     ctor, states = loads(serialized)
2022-04-04T14:06:44.800940+00:00 app[web.1]: AttributeError: Can't get attribute '_rebuild_function' on <module 'numba.core.serialize' from '/app/.heroku/python/lib/python3.8/site-packages/numba/core/serialize.py'>
2022-04-04T14:06:44.801236+00:00 app[web.1]: [2022-04-04 14:06:44 +0000] [10] [INFO] Worker exiting (pid: 10)
2022-04-04T14:06:45.708340+00:00 app[web.1]: [2022-04-04 14:06:45 +0000] [4] [WARNING] Worker with pid 10 was terminated due to signal 15
2022-04-04T14:06:45.794901+00:00 app[web.1]: [2022-04-04 14:06:45 +0000] [4] [INFO] Shutting down: Master
2022-04-04T14:06:45.794945+00:00 app[web.1]: [2022-04-04 14:06:45 +0000] [4] [INFO] Reason: Worker failed to boot.
2022-04-04T14:06:45.943504+00:00 heroku[web.1]: Process exited with status 3
2022-04-04T14:06:46.198627+00:00 heroku[web.1]: State changed from up to crashed
2022-04-04T14:26:03.163411+00:00 heroku[web.1]: State changed from crashed to starting
...


Best
[ed-test-app.zip](https://github.com/oegedijk/explainerdashboard/files/8410923/ed-test-app.zip)

Xin

**Comment by eakande** [comment]
I just ran your code and it ran well on my local machine, not yet deploy it: If you use 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)
print(X_train.shape,y_train.shape,X_test.shape,y_test.shape)



model = RandomForestClassifier(n_estimators = 400,
                           n_jobs = -1,
                           oob_score = True,
                           bootstrap = True,
                            max_depth=5,
                           random_state = 42)
model.fit(X_train, y_train.values.ravel())
model.score(X_train,y_train), model.score(X_test,y_test), model.oob_score_

explainer = RegressionExplainer(model, X_test, y_test)


explainer = ClassifierExplainer(model, X, y)
explainer.dump("explainer.joblib")

then run it with "explainerdashboard run explainer.joblib"

if you use yaml.

db = ExplainerDashboard(explainer)
db.to_yaml("dashboard.yaml", explainerfile="explainer.joblib")

run it with 
explainerdashboard run dashboard.yaml

**Comment by achimgaedke** [comment]
returning to the initial topic of this thread, this is an upstream bug: https://github.com/plotly/dash/issues/1992

This is fixed with [dash-2.3.1](https://github.com/plotly/dash/releases/tag/v2.3.1) - see my commit above.

**Comment by oegedijk** [comment]
This was fixed temporarily and now is even fixed upstream so closing this issue...
