### ISSUE TITLE
Dashboard Components

### ISSUE THREAD

**Issue by eakande** [oegedijk/explainerdashboard#204]
Hello Oegedijk, I ran the explainer component below to assess the shape contribution table but the compute gave me "class" syntax error. 
class 
explainerdashboard.dashboard_components.shap_components.ShapContributionsTableComponent(explainer, title='Contributions Table', name=None, subtitle='How has each feature contributed to the prediction?', hide_title=False, hide_subtitle=False, hide_index=False, hide_depth=False, hide_sort=False, hide_selector=False, feature_input_component=None, index_dropdown=True, pos_label=None, index=None, depth=None, sort='abs', description=None, **kwargs)

However, if I removed the class I have the follow object as output " <explainerdashboard.dashboard_components.composites.ShapContributionsTableComponent object at 0x000001A6EC23EB20>

Could you please show me the step on how to assess this output?

**Comment by oegedijk** [comment]
euhm, I guess you would want to do something like this:

```
from explainerdashboard.custom import *

class CustomDashboard(ExplainerComponent):
    def __init__(self, explainer, name=None, **kwargs):
        super().__init__(explainer, title="Custom Dashboard")
        self.table = ShapContributionsTableComponent(explainer)

    def layout(self):
        return dbc.Container([
            dbc.Row([
                dbc.Col([
                    html.H1("Custom table Demonstration:"),
                    self.table.layout()
                ])
            ]),
        ])

db = ExplainerDashboard(explainer, CustomDashboard, hide_header=True)
db.run()

```

**Comment by oegedijk** [comment]
did this help? Closing this for now...
