### ISSUE TITLE
Update conda version

### ISSUE THREAD

**Issue by tvdboom** [oegedijk/explainerdashboard#230]
I noticed conda is behind on version: https://github.com/conda-forge/explainerdashboard-feedstock/pull/41/

**Comment by tvdboom** [comment]
It fails because it can't find `requirements.txt` when running setup.py. You may need a `MANIFEST.in` file. Not 100% sure that's the problem though

**Comment by oegedijk** [comment]
new years resolution: fix the conda package of explainerdashboard.

Just released another version, but the condaforge build failed again: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=634959&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=636

@tvdboom you have any conda experience and are able to help me debug?

**Comment by oegedijk** [comment]
@tvdboom update: the MANIFEST.in trick helped. But then ran into some issues with the latest versions of numba and numpy not playing nice together.  Pinned numpy to `<1.24` for now. 

But now running into the issue of the `dash-auth` package not being updated to dash v2, which results in import errors, which results in the build failing. There is a PR, but plotly does not seem in a hurry to merge it. Will try to contact some people inside plotly to see if we can speed it along https://github.com/plotly/dash-auth/pull/125

**Comment by tvdboom** [comment]
Thanks for the update @oegedijk. I don't have any experience with dash so can't help with that unfortunately...

**Comment by oegedijk** [comment]
Should be fixed now! (version 0.4.2 is on conda-forge, although the badge on the README still seem cached and outdated)
