### ISSUE TITLE
Cannot Import library due to Shap

### ISSUE THREAD

**Issue by AmitSri21** [oegedijk/explainerdashboard#238]
Cannot Import explainer dashboard as it throws cannot find module numba.core

Tried installing numba 0.48.0 but can't get it running 

Please help

**Comment by oegedijk** [comment]
Hi @AmitSri21, have you tried installing the library in a fresh virtual environment? Does it still show give the error?

e.g.
```
$ python -m venv venv
$ source venv/bin/activate
$ pip install explainerdashboard
```
