### ISSUE TITLE
Cannot pass cutoff to ClassifierModelStatsComposite

### ISSUE THREAD

**Issue by plotxy** [oegedijk/explainerdashboard#239]
Hello,

I'm trying to incorporate ClassifierModelStatsComposite in a report we use. Everything so far worked very well, beside for the ability to choose a different cutoff that the default one.

What I do is create my eplainer, and then pass it to the composite instance.
explainer = ClassifierExplainer(model, X], y)
stats = ClassifierModelStatsComposite(explainer)

I would like to be able to have a cutoff of, let's say, 0.8 instead of the 0.5. How do I do that?

I tried pass it it directly to ClassifierModelStatsComposite or to .to_html(). But neither for me worked.

I don't understand if I should pass a dictionary like {'cutoff': 0.8, 'binary': True} or something like {'confusionmatrix-cutoff-id02': 0.8}.
Anyway, neither of the two works for me.

What's the correct way?

I'm using version 0.4.0.

**Comment by plotxy** [comment]
I'm not sure, but I think I found what may be the issue:

In the class ClassifierModelStatsComposite when all the different component are initiated the cutoff is never passed as an argument.
The cutoff at the level of the composite is initiated and stats.cutoff shows the correct one.
But then is never passed to the components creating the charts: even if passing a dictionary as kwargs to the composite, the kwargs are not automatically passed to the component.
Maybe in your code you were supposed to use your decorator delegates_kwargs?
I modified the code to add a kwargs = {'bin_size': bin_size, 'quantiles': quantiles, 'cutoff': cutoff} before initiating the components and seems to work now.

And in the to_html function of the different components, I have the impression that when you use get_state_args this always returns and empty dictionary and therefore the inability to pass anything here.

**Comment by oegedijk** [comment]
Hi @plotxy good catch! the `cutoff` parameter was indeed not passed down to the `CutoffPercentileComponent`. Simple one line fix, so should be in the next release. But the kwargs are passed down to the `CutoffPercentileComponent` so if you hand define the kwargs with `kwargs=dict(cutoff=0.6)` then that should indeed also work in the meantime!

**Comment by oegedijk** [comment]
The composites do not have any state themselves so they also don't have any state args (all the state is in their subcomponents). So e.g.:


```
>>>ClassifierModelStatsComposite(explainer, cutoff=0.6).get_state_args()
{}
>>>ClassifierModelStatsComposite(explainer, cutoff=0.6).liftcurve.get_state_args()
{'cutoff': 0.5, 'percentage': True, 'wizard': True, 'pos_label': None}
```

**Comment by oegedijk** [comment]
Should be in the release that just went out.

Happy new year!
