### ISSUE TITLE
v0.3.8 is breaking due to changes in dtreeviz API

### ISSUE THREAD

**Issue by sinha1** [oegedijk/explainerdashboard#248]
Hi,

At the moment we are using v0.3.8 which no longer works due to changes in dtreeviz API. Can I request to pin the version of dtreeviz for v0.3.8 release to protect from breaking changes in dtreeviz v2 API. Thank you!

`ImportError: cannot import name 'dtreeviz' from 'dtreeviz.trees'`

**Comment by oegedijk** [comment]
Hi, just released version 0.4.2 to conda that should fix this issue! Let me know if it worked for you!
