### ISSUE TITLE
Feature Request: Option to rename "index"

### ISSUE THREAD

**Issue by raybellwaves** [oegedijk/explainerdashboard#25]
I imagine the term "index" is confusing to the lay person.

Could the term "index" be changed by the user? e.g. for the titanic example "index" could be changed to "person".

![image](https://user-images.githubusercontent.com/17162724/99453093-72e8fb00-28f2-11eb-8de1-70a2af43c34f.png)

**Comment by raybellwaves** [comment]
Could look for X.index.name or an extra arg such as "idx_name"

**Comment by oegedijk** [comment]
Excellent! Yes will add this!

**Comment by oegedijk** [comment]
Done! Will be in the next release! Thanks for the suggestion!

**Comment by oegedijk** [comment]
Just releases 0.2.11 with this feature...
