### ISSUE TITLE
explainer.decisiontree function is not working 

### ISSUE THREAD

**Issue by tclo** [oegedijk/explainerdashboard#252]
Some error message popped up when I run the codes below. Is there someone know how to fix this issue?
The versions of I installed is 
1) explainerdashboard is  0.4.1.1.
2) graphviz is windows_10_cmake_Release_graphviz-install-7.1.0-win64.exe

#################################### My codes #################################
from explainerdashboard import ClassifierExplainer
from sklearn.ensemble import RandomForestClassifier
from explainerdashboard.datasets import titanic_survive, titanic_names, feature_descriptions

X_train, y_train, X_test, y_test = titanic_survive()
train_names, test_names = titanic_names()

model = RandomForestClassifier(n_estimators=50, max_depth=5)
model.fit(X_train, y_train)

explainer = ClassifierExplainer(model, X_test, y_test, 
                                cats=['Sex', 'Deck', 'Embarked'], 
                                idxs=test_names)

name = test_names[20]
print(name)# first row of X_test
explainer.plot_trees(name, highlight_tree=20)

explainer.get_decisionpath_df(tree_idx=20, index=name)

explainer.get_decisionpath_summary_df(tree_idx=5, index=name)

explainer.decisiontree(tree_idx=5, index=name)

######################################## Error message ################################
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[4], line 23
     19 explainer.get_decisionpath_df(tree_idx=20, index=name)
     21 explainer.get_decisionpath_summary_df(tree_idx=5, index=name)
---> 23 explainer.decisiontree(tree_idx=5, index=name)

File D:\ProgramFiles\anaconda3\envs\xai\lib\site-packages\explainerdashboard\explainers.py:3674, in TreeExplainer.decisiontree(self, tree_idx, index, show_just_path)
   3671     return None
   3673 from IPython.display import SVG
-> 3674 svg_file = self.decisiontree_file(tree_idx, index, show_just_path)
   3675 return SVG(open(svg_file,'rb').read())

File D:\ProgramFiles\anaconda3\envs\xai\lib\site-packages\explainerdashboard\explainers.py:3648, in TreeExplainer.decisiontree_file(self, tree_idx, index, show_just_path)
   3645     print("No graphviz 'dot' executable available!") 
   3646     return None
-> 3648 viz = dtreeviz(self.shadow_trees[tree_idx], 
   3649                 X=self.get_X_row(index).squeeze(), 
   3650                 fancy=False,
   3651                 show_node_labels = False,
   3652                 show_just_path=show_just_path) 
   3653 return viz.save_svg()

File D:\ProgramFiles\anaconda3\envs\xai\lib\site-packages\dtreeviz\compatibility.py:254, in dtreeviz(tree_model, X_train, y_train, feature_names, target_name, class_names, tree_index, precision, orientation, instance_orientation, show_root_edge_labels, show_node_labels, show_just_path, fancy, histtype, highlight_path, X, max_X_features_LR, max_X_features_TD, depth_range_to_display, label_fontsize, ticks_fontsize, fontname, title, title_fontsize, colors, scale)
    251 shadow_tree = ShadowDecTree.get_shadow_tree(tree_model, X_train, y_train, feature_names, target_name, class_names,
    252                                             tree_index)
    253 model = DTreeVizAPI(shadow_tree)
--> 254 return model.view(precision, orientation,
    255                   instance_orientation,
    256                   show_root_edge_labels, show_node_labels, show_just_path, fancy, histtype, highlight_path, X,
    257                   max_X_features_LR, max_X_features_TD, depth_range_to_display, label_fontsize, ticks_fontsize,
    258                   fontname, title, title_fontsize, colors, scale)

File D:\ProgramFiles\anaconda3\envs\xai\lib\site-packages\dtreeviz\trees.py:455, in DTreeVizAPI.view(self, precision, orientation, instance_orientation, show_root_edge_labels, show_node_labels, show_just_path, fancy, histtype, leaftype, highlight_path, x, max_X_features_LR, max_X_features_TD, depth_range_to_display, label_fontsize, ticks_fontsize, fontname, title, title_fontsize, colors, scale)
    451         return self.shadow_tree.leaves
    453 n_classes = self.shadow_tree.nclasses()
--> 455 colors = adjust_colors(colors, n_classes)
    458 if orientation == "TD":
    459     ranksep = ".2"

File D:\ProgramFiles\anaconda3\envs\xai\lib\site-packages\dtreeviz\colors.py:119, in adjust_colors(colors, n_classes, cmp)
    116         COLORS["classes"] = get_hex_colors(n_classes, cmp)
    117     return COLORS
--> 119 return dict(COLORS, **colors)

TypeError: dict() argument after ** must be a mapping, not float

**Comment by oegedijk** [comment]
This is an issue with dtreeviz 2.0 is you downgrade it should work. Will try to find time this weekend to push a fix...

**Comment by oegedijk** [comment]
Just released v0.4.2 which I think should fix this issue. Could you check if it fixed it for you? @tclo
