### ISSUE TITLE
option to change colors of waterfall plot

### ISSUE THREAD

**Issue by raybellwaves** [oegedijk/explainerdashboard#26]
I understand shap plots use red for positive (up) and blue for negative (down).

From a lay person point of view they are probably use to seeing green for positive (up), red for negative (down) and blue for final.

It would be nice to have an option to `ExplainerDashboard` to do this. e.g. `waterfall_plot_colors='rg'`

![image](https://user-images.githubusercontent.com/17162724/99561204-b5fbaa80-2994-11eb-9782-d60e7ab2a845.png)

**Comment by raybellwaves** [comment]
Some discussion here: https://github.com/slundberg/shap/issues/62

Probably can be changed here: https://github.com/oegedijk/explainerdashboard/blob/fc80e0b65a679f09865a829a33d0406a165b16de/explainerdashboard/dashboard_components/shap_components.py#L728

But would be good to do a simple test with shap outside of explainerdashboard.

**Comment by oegedijk** [comment]
Done! Also added a parameter to `explainer.plot_shap_contributions(index, higher_is_better=False)` to flip the red and the green. Not sure whether to add this to the `ShapContributionsGraphComponent`, as there are already quite a lot of toggles there, what do you think?

**Comment by raybellwaves** [comment]
> Done!

Awesome! Although don't see any commits. Maybe you still have to push?

> there are already quite a lot of toggles there, what do you think?

Good question. Some of the toggles could be dropped from the dashboard and added as args to `ExplainerDashboard`. 

E.g. for the Individual Predictions tab I probably want to hide the Orientation toggle in the Contributions to prediction plot. To the lay person this may be noise. No idea where but I could imagine something like `ExplainerDashboard(..., orientation_toggle='vertical')` (with default orientation_toggle=None). This sets the orientation of the plot to be vertical and there is no orientation toggle.

**Comment by raybellwaves** [comment]
> hide the [Orientation/X] toggle

Actually this may already be in here:
https://explainerdashboard.readthedocs.io/en/latest/index.html#custom-dashboards

**Comment by oegedijk** [comment]
> E.g. for the Individual Predictions tab I probably want to hide the Orientation toggle in the Contributions to prediction plot. To the lay person this may be noise. No idea where but I could imagine something like `ExplainerDashboard(..., orientation_toggle='vertical')` (with default orientation_toggle=None). This sets the orientation of the plot to be vertical and there is no orientation toggle.

While fixing the red/green colors thing, I also made sure that `**kwargs` to ExplainerDashboard now get passed down to all the components. Which means that you can do:

`ExplainerDashboard(explainer,  orientation='horizontal', hide_orientation=True).run()` 

Do be mindful of unintented consequences as kwargs are passed down to **all** components.

**Comment by oegedijk** [comment]
> > Done!
> 
> Awesome! Although don't see any commits. Maybe you still have to push?
> 
 I hadn't pushed it yet as there was some other stuff I had to clean up first. But just released it now. 

Also: added tooltips like pixie dust all over the dashboard, in order to explainer the explainerdashboard itself a bit better. Hopefully that should also help people working with it.
