### ISSUE TITLE
explaindashboard failed to run 

### ISSUE THREAD

**Issue by DAVINDERYADAVRJIT** [oegedijk/explainerdashboard#261]
I downgrade to override the flask issue and ends up with 
AttributeError: module 'numpy' has no attribute 'bool'.

piece of code I'm running is what has been shared as Example of use  
![image](https://user-images.githubusercontent.com/24229487/235917795-43f3d417-0534-4eb7-842c-c4f9f694ccca.png)

**Comment by oegedijk** [comment]
yeah, seems to be incompatibilility with the shap library and numpy 1.24, so you need to downgrade to numpy==1.23

Just did a release that pins the numpy dependency for now...
