### ISSUE TITLE
dtreeviz update breaks ClassifierExplainer import

### ISSUE THREAD

**Issue by mgruddy** [oegedijk/explainerdashboard#264]
dtreeviz was recently updated to 2.2.1 and importing ClassifierExplainer causes an error in the importation of dtreeviz functions.

**Comment by oegedijk** [comment]
Hi @mgruddy,

I am not able to replicate this on my side, what error do you get?

**Comment by mgruddy** [comment]
Apologies on my end. I had an older version of explainerdashboard and did not realize it!
