### ISSUE TITLE
Dashboard is not running correctly when I am trying to use saved joblib file.

### ISSUE THREAD

**Issue by jacob143590** [oegedijk/explainerdashboard#285]
I am using following code to save the dashboard in joblib format.
`
explainer = ClassifierExplainer(model, X, y)
explainer.dump("explainer.joblib")
`
It is correctly saved as explainer.joblib.

When api request is called from frontend, I try to run the dashboard using 
`import os
os.system("npx kill-port 8050")
os.system('explainerdashboard run explainer.joblib')
`
But I can't get the result.
Could you tell me how to run the saved dashboard without training the model with csv file?
Thank you in advance.

**Comment by Sajalj98** [comment]
similar issue for me, i tried saving using to_yaml() and loading using from_config()
It just shows loading and nothing happens.
Please provide a workaround

**Comment by oegedijk** [comment]
What do you mean with "I can't get the result"? Do you get an error message?

**Comment by jacob143590** [comment]
I solved it using following code.
`explainer, CustomDashboard, CustomPredictionsTab, Classif = flask_main(x_train, x_test, y_train, y_test, catCols,
                                                                     model_id)
explainer.dump("joblib.joblib")`
