### ISSUE TITLE
Request: Plotting parameters in WhatifComponent

### ISSUE THREAD

**Issue by hkoppen** [oegedijk/explainerdashboard#30]
As far as I can see, WhatifComponent includes ShapContributionsGraphComponent, but does not include plot styling parameters such as "sort" and "orientation". I think it makes sens to add these :-)

**Comment by hkoppen** [comment]
Okay :) alternatively, one could make the "edit feature input" component accessible?

**Comment by oegedijk** [comment]
Just refactored the `WhatIfComponent` into a `FeaturesInputComponent` that you can connect with either a `ShapContributionsGraphComponent` or a `PdpComponent`:

```python
self.input = FeatureInputComponent(explainer)
self.contrib = ShapContributionsGraphComponent(explainer, 
                        feature_input_component=self.input)
self.pdp = PdpComponent(explainer, feature_input_component=self.input)

def layout(self):
    return html.Div([self.input.layout, self.contrib.layout(), self.pdp.layout()])
```

**Comment by oegedijk** [comment]
This also means that the contributions graph and pdp graph have all the same dropdown and toggles as on the individual predictions tab.
