### ISSUE TITLE
RandomIndex and FeatureInput not usable at the same time (anymore)

### ISSUE THREAD

**Issue by hkoppen** [oegedijk/explainerdashboard#34]
I updated on 0.2.13 and I'm really liking the cards, thanks for that! Actually, I wrapped my components into dbc.Cards before...😁 

Reworking my WhatIfTab I found that RegressionRandomIndexComponent and FeatureInputComponent are not getting along. Is this intended? More precisely, if my class looks like

```
self.index = RegressionRandomIndexComponent(explainer,
                                                    hide_title=False, hide_index=False,
                                                    hide_slider=True, hide_labels=True,
                                                    hide_pred_or_perc=True,
                                                    hide_selector=True, hide_button=False)

self.input = FeatureInputComponent(explainer)
        
self.contributions = ShapContributionsGraphComponent(explainer, depth=7,
                                                             hide_title=False, hide_index=False,
                                                             hide_depth=True, hide_sort=True,
                                                             hide_orientation=True, hide_cats=True,
                                                             hide_selector=True,
                                                             feature_input_component=self.input
                                                             )
        
self.connector = IndexConnector(self.index, [self.contributions])
```

the SHAP plot only refreshes after changing in the FeatureInputComponent. If I remove _feature_input_component=self.input_, it (obviously) only refreshes after hitting "Random Index".

Edit: This is probably connected with forcing hide_index=True when using FeatureInputComponent aswell. Is this strictly neccessary or only convenient for implementation reasons?

**Comment by oegedijk** [comment]
Ah yes, that is (sort of) intended: the contributions graph either updates with a FeatureInputComponent trigger or with the index trigger. 

Reason being that each output element can have only one callback associated with it in dash. So when you specify a `feature_input_component` then you get one callback that excludes the index (and the index gets hidden as well on the contributions component).

So the way to do it is to connect the RandomIndexSelector to the FeatureInputComponent (and then the FeatureInputComponent connects to the contributions graph):

```
self.connector = IndexConnector(self.index, [self.input])
```

**Comment by hkoppen** [comment]
Ah, great, thanks!
