### ISSUE TITLE
Including feature dropped in One-Hot-Encoding to cats / FeatureInputComponent

### ISSUE THREAD

**Issue by hkoppen** [oegedijk/explainerdashboard#36]
I just realized that there is a parameter cats - grouping one-hot-encoded variables back together is a thing I'm missing in Python since forever, great stuff! In particular, it simplifies the otherwise huge FeatureInputComponent. 

However, I'm usually dropping one level when encoding, which is of course missing in the respective dropdown menu in FeatureInputComponent. Is it possible to include the dropped level so that it can be chosen in FeatureInputComponent as well?

**Comment by oegedijk** [comment]
In the contributions plot/table the missing category (so if all onehot columns are 0) are denoted NOT_ENCODED. So I guess I could add those to the drop downs as well. Might be confusing to the average user though.

Not sure what a clean syntax would be to pass a proper name to for the not encoded category to the `cats` parameter though.
With a tuple like this?
```
cats={'Deck': (['Deck_A', 'Deck_B'], 'Deck_OTHER)}
```

**Comment by oegedijk** [comment]
Also: unless you are using linear models, there really is no need to drop a level. Tree based models don't have to invert matrices so collinearity is not a problem.

**Comment by hkoppen** [comment]
Yes, maybe calling it 'Deck_dropped'?

True.  I'm using a tree 😁

**Comment by oegedijk** [comment]
So instead of trying to fold it into the `cats` parameter, I'm thinking of adding an additional parameter `cats_not_encoded`, like this:

```
explainer = ClassifierExplainer(model, X_test, y_test, 
                                cats=['Deck', 'Embarked',
                                    {'Gender': ['Sex_male', 'Sex_female', 'Sex_nan']}]),
                                cats_not_encoded = dict(Deck='Unknown Deck',  Embarked='Embarked elsewhere', Gender='Other Gender')
)
```

Still need to actually make it work though :)

**Comment by oegedijk** [comment]
Added this to the `dev` branch: https://github.com/oegedijk/explainerdashboard/tree/dev

You can pass a `cats_missing` parameter to set the missing string. E.g. `cats_missing={'Sex': 'Gender not known'}, to override the default description which is 'NOT_ENCODED'.

You can try it out if you have the time.

**Comment by oegedijk** [comment]
https://github.com/oegedijk/explainerdashboard/releases/tag/v0.3.2
