### ISSUE TITLE
to_yaml misses some kwargs e.g. no_permutations

### ISSUE THREAD

**Issue by raybellwaves** [oegedijk/explainerdashboard#40]
I'm adding a few settings to the dashboard then saving as a yaml file

```
db = ExplainerDashboard(
    explainer,
    importances=False,
    model_summary=False,
    decision_trees=False,
    no_permutations=True,
    hide_depth=True,
    hide_pdp=True,
    title=title,
)
db.to_yaml("config/dashboard.yaml", explainerfile="config/explainer.joblib")
```

When loading the yaml it is missing some of these key works.

e.g. no_permutations, hide_depth, hide_pdp

I'm aware these are **kwargs to ExplainerComponents but it would be nice if the `to_yaml` also captured https://explainerdashboard.readthedocs.io/en/latest/custom.html?highlight=no_permutations#passing-parameters-as-kwargs

**Comment by oegedijk** [comment]
Yes, just happened to have fixed this today actually! Will be in the next release!

Will also be possible to add additional `**kwargs` from loading `.from_config()`

**Comment by raybellwaves** [comment]
> Will also be possible to add additional **kwargs from loading .from_config()

Great. Will be very useful for this https://explainerdashboard.readthedocs.io/en/latest/deployment.html?highlight=auth#setting-logins-and-password

**Comment by oegedijk** [comment]
Just pushed this to release v0.2.14. Have yet to update the docs, but should be pretty straightforward...

**Comment by raybellwaves** [comment]
Cheers. Yeah got it

https://explainerdashboard.readthedocs.io/en/latest/deployment.html#storing-custom-dashboard-config-and-running-with-gunicorn

```
db = ExplainerDashboard.from_config("dashboard.yaml", higher_is_better=False)
```
