### ISSUE TITLE
how to hide partial dependence plots?

### ISSUE THREAD

**Issue by raybellwaves** [oegedijk/explainerdashboard#41]
AFAIK the key `hide_pdp` should hide the pdp plot (from all components?)

When running
```
db = ExplainerDashboard(
    explainer,
    hide_pdp=True,
)
```

It doesn't seem to remove the pdp plots from any tabs (Individual Predictions, What if...)

**Comment by oegedijk** [comment]
Ah, right now it's not possible yet to hide entire components from the dashboard. My idea was that when you really want to customize which components to show, you can simply build your own custom layout. But actually it should be possible to add some flags for that as well for the default dashboard...

Let me have a look...

**Comment by oegedijk** [comment]
done! Will be in next release...

**Comment by oegedijk** [comment]
`hide_pdp=True` now works!
