### ISSUE TITLE
add explainerhub to docs

### ISSUE THREAD

**Issue by raybellwaves** [oegedijk/explainerdashboard#50]
https://github.com/oegedijk/explainerdashboard/releases/tag/v0.2.17

Looks good

Perhaps a new page here? https://explainerdashboard.readthedocs.io/en/latest/deployment.html

**Comment by oegedijk** [comment]
Yeah, gonna give it its own special section in the docs, and probably also gonna add a special CLI. Still working out some kinks now, so it's kind of a hidden feature for now :)

Working on user management now. The `dash-auth` doesn't seem to work really well when you have multiple dashboards hosted on multiple Flask routes. But gonna add some lightweight `Flask-Login` user management (including giving permissions to specific dashboards on the Hub.
