### ISSUE TITLE
Decision trees tab for Catboost?

### ISSUE THREAD

**Issue by oleg-savko** [oegedijk/explainerdashboard#55]
Do you have plan to support decision trees tab for catboost model like for xgboost and random forest?

**Comment by oegedijk** [comment]
The decision trees visualisation depends on the `dtreeviz` package ([https://github.com/parrt/dtreeviz](https://github.com/parrt/dtreeviz)). Currently they do not support `catboost `and `lightgbm`, although support for the latter is in the works. Maybe you could see if you can help out with `catboost` support, would be cool!
