### ISSUE TITLE
Error due to check_additivity

### ISSUE THREAD

**Issue by sparvaneh** [oegedijk/explainerdashboard#56]
Hi,

I am getting the following error message for the random forest model:
Exception: Additivity check failed in TreeExplainer! Please ensure the data matrix you passed to the explainer is the same shape that the model was trained on. If your data shape is correct then please report this on GitHub. Consider retrying with the feature_perturbation='interventional' option. This check failed because for one of the samples the sum of the SHAP values was 0.626204, while the model output was 0.710000. If this difference is acceptable you can set check_additivity=False to disable this check.

Do you have any suggestion to solve the issue?

Thanks,
Saman

**Comment by oegedijk** [comment]
When do you get this message? 

I sometimes get a similar error from the what if contributions component the second time I start a particular dashboard on the first load, but not when you select further indexes. (Highly peculiar, and I still have to further investigate that bug)

Do you get this error consistently? Or just randomly? It's probably a `shap` issue, so does it replicate when you generate the shap values directly yourself?

**Comment by sparvaneh** [comment]
It is happening consistently. It is a shap issue as it happens even when I generate the shap values directly. Although this issue is not related to your great dashboard, I would appreciate any hint to resolve the issue

**Comment by oegedijk** [comment]
Have you updated to the latest version of shap (0.37)? Otherwise you could try installing from the master branch directly, sometimes there are bug fixes there that are not released yet.

And open an issue in the [shap repo](https://github.com/slundberg/shap/issues)!
