### ISSUE TITLE
include [something] from dalex?

### ISSUE THREAD

**Issue by raybellwaves** [oegedijk/explainerdashboard#58]
Recently learned about https://github.com/ModelOriented/DALEX

https://github.com/ModelOriented/DALEX/tree/master/python/dalex

Haven't had chance to look into it but may be of interest for this repo. If I have something specific in mind i'll come back and edit this.

maybe something for fairness: https://dalex.drwhy.ai/python-dalex-fairness.html

**Comment by oegedijk** [comment]
Ah, yeah, looks cool. I am planning to add a fairness tab (or group comparison tab), where you can compare outcomes and predictions across groups (maybe even compare shap values across groups), and show some fairness metrics. Don't know when I'll have the time though...

**Comment by oegedijk** [comment]
closing this for now...
