### ISSUE TITLE
Seperating global vs local explanation and adding what-if analysis under local explanation?

### ISSUE THREAD

**Issue by rezacsedu** [oegedijk/explainerdashboard#6]
As the title suggests, is there a plan of adding such functionality?

**Comment by oegedijk** [comment]
Hi,

Not sure if I understand the question, but SHAP values offer both local and global explanations (shap contributions, mean abs shap importances and shap dependence plots respectively), and the PDP plots offer what-if functionality (albeit for only a single feature at a time).

Or are you talking about adding LIME values? I've been thinking about adding them, but haven't come up with a good way of making them convenient yet. There are a lot of decisions to make in terms of kernel size, sampling function, local model, etc. And then the interpretation of the LIME values itself is not so easy to explain. But it's on the TODO list!

Also thinking about a functionality to experiment with changing multiple features at the same time or consecutively for what-if scenarios.

What kind of functionality would you like to see exactly?

**Comment by rezacsedu** [comment]
>>> Also thinking about functionality to experiment with changing multiple features at the same time or consecutively for what-if scenarios.

That's what I was expecting. ExplianX (see: https://github.com/explainX/explainx), for example, provides similar functionality, under local perturbations. 

![image](https://user-images.githubusercontent.com/14220009/95002288-6d4d8500-05d2-11eb-85c4-b33797341b3b.png)

**Comment by oegedijk** [comment]
Ah, gotcha. Yeah, that shouldn't be too hard to build. Can put it on the roadmap!

**Comment by oegedijk** [comment]
Done! Added a whatif component and tab to the latest release (among other cool stuff). There's still a bit of tweaking to be done (thinking of including it in the individual predictions tab, but that will take a bit more plumbing), but this is a first start. 

You can see the tab at: [http://titanicexplainer.herokuapp.com/classifier/](http://titanicexplainer.herokuapp.com/classifier/)

Is this something like what you had in mind? Anything else you would like to see?
