### ISSUE TITLE
Showing observed label in ClassifierPredictionSummaryComponent 

### ISSUE THREAD

**Issue by sparvaneh** [oegedijk/explainerdashboard#60]
Hi,

I am using feature_input_component to link ClassifierPredictionSummaryComponent to FeatureInputComponent. Changing index in FeatureInputComponent correctly change table and pie chart in ClassifierPredictionSummaryComponent. However, the observed label * indicator is not working in this case.

Thanks,

**Comment by oegedijk** [comment]
Hi,

When you use the FeatureInputComponent you are creating a new row of data so by definition you do not have an observed label for that new data (you are creating a counterfactual after all).


However you could add another ClassifierPredictionSummaryComponent that is simply linked to an index selector, and then it would display the observed label for a particular index.

**Comment by sparvaneh** [comment]
Thank you for your response. When I select an index in FeatureInputComponent, it is like selecting from available data that might have an observed label. Just as a _suggestion_, it will be helpful to show an observed label if a) an index is selected using FeatureInputComponent, and b) a label for the selected index is available. 
Is using FeatureInputComponent, override showing index in ClassifierPredictionSummaryComponent?

Thanks,
Saman
