### ISSUE TITLE
random uuid with seed

### ISSUE THREAD

**Issue by oegedijk** [oegedijk/explainerdashboard#69]
Is there a reason why you are using UUIDs in the first place? Thinking you could just set seed and do randomization with numbers to get deterministic names.

E.g line 177 in dashboard_methods.py
`        if not hasattr(self, "name") or self.name is None:
            self.name = name or "uuid"+shortuuid.ShortUUID().random(length=5)
`

_Originally posted by @carlryn in https://github.com/oegedijk/explainerdashboard/issues/38#issuecomment-758700981_

**Comment by oegedijk** [comment]
Original goal was to generate a unique name that is both short and url-friendly (planning on adding querystring support at some point). But I guess that could be done simpler and without the shortuuid dependency, e.g.: https://proinsias.github.io/til/Python-UUID-generate-random-but-reproducible-with-seed/

Got a code suggestion?

**Comment by yanhong-zhao-ef** [comment]
This is an interesting one as I deployed the app with gunicorn and there seemed to be some problems with matching callback to their ids. As I dug a bit deeper and it seems like gunicorn spawns multiple python processes with multiple workers so depends on the worker serving the app to specific users some of the plots might not be generated as that worker fails to retrieve the callbacks. I have fixed the names for the tabs and components and that problem seems to have gone away.

Not sure that is exactly the reason causing it but that is my hypothesis for now.

**Comment by oegedijk** [comment]
Do you have a code example and did you update to the latest release? If you use the default dashboard this should now be fixed, so curious about your code..

**Comment by yanhong-zhao-ef** [comment]
I built a custom dashboard and here it is https://github.com/jackchua/nga-ui/blob/gat-ltv-monitoring/dash_apps/gat_ltv_monitor.py

**Comment by oegedijk** [comment]
Very nice! Do you have it deployed somewhere? 

And a heads up: part of the refactoring of the upcoming `0.3` release involved turning some `@property` attributes into regular methods, so that the `calculate_dependencies()` method now reads:

```python
def calculate_dependencies(self):
        """calls all properties in self.dependencies so that they get calculated
        up front. This is useful to do before starting a dashboard, so you don't
        compute properties multiple times in parallel."""
        for dep in self.dependencies:
            try:
                attribute = getattr(self.explainer, dep)
                if callable(attribute):
                    _ = attribute()
            except:
                ValueError(f"Failed to generate dependency '{dep}': "
                    "Failed to calculate or retrieve explainer property explainer.{dep}...")
```

Note the:

```
if callable(attribute):
    _ = attribute()
```

**Comment by oegedijk** [comment]
Once you have it deployed somewhere, you can share it here: https://github.com/oegedijk/explainerdashboard/discussions/45

**Comment by oegedijk** [comment]
Instead of setting the seed of the random `uuid` process, I solved with with setting a determinative generator:

```python
def id_generator():
    """generator that generatores unique consecutive id's starting with 'id' + number
    
    Can be reset with reset_id_generator()"""
    i = 1
    while True:
        yield 'id'+str(i)
        i += 1

def reset_id_generator():
    """resets the global id generator"""
    global id_gen
    id_gen = id_generator()

def yield_id():
    """yields the next unique consecutive id. Reset using reset_id_generator()"""
    global id_gen
    return next(id_gen)

reset_id_generator()
```

Set for next release...
