### ISSUE TITLE
dash.dependencies.Input Error

### ISSUE THREAD

**Issue by seragizozel** [oegedijk/explainerdashboard#71]
Hello Mr. Oegedijk,

I was trying to run sample code however, I continuously get this error. 
"IncorrectTypeException: The input argument `pdp-col-33.value` must be a list or tuple of
`dash.dependencies.Input`s."
I tried many different ways, but I couldn't solve the issue. Could you please help me how I can solve the problem? 

Thank you,
Sera

**Comment by oegedijk** [comment]
Hi Sera,

Could you try updating you `dash` installation? `pip install -U dash`

In a more recent version of dash, you don't have to pass lists of input and state elements, as long as they are in the right order.

So in the old dash you would have to do write:

```python
@app.callback(
            Output('pdp-categories-sort-div-'+self.name, 'style'),
            [Input('pdp-col-'+self.name, 'value')]
        )
        def update_pdp_sort_div(col):
            return {} if col in self.explainer.cat_cols else dict(display="none")
```

but in the new dash you can do:

```python
@app.callback(
            Output('pdp-categories-sort-div-'+self.name, 'style'),
            Input('pdp-col-'+self.name, 'value')
        )
        def update_pdp_sort_div(col):
            return {} if col in self.explainer.cat_cols else dict(display="none")
```

Anyway, I should write the callbacks in such a way that they even work with older versions of dash, but must have slipped into the habit of the new style.

**Comment by oegedijk** [comment]
@seragizozel did that fix your issue? Can I close it?

**Comment by gboaviagem** [comment]
@oegedijk I was facing the exact same problem and your solution worked beautifully. I had dash-1.13.4 and upgraded to dash-1.19.0. Thank you.

**Comment by oegedijk** [comment]
Great! Will put a requirement in of dash>=1.19, so that is updates automatically for users that have an older version installed.
