### ISSUE TITLE
Replace metric in table Model Performance Metric

### ISSUE THREAD

**Issue by mvpalheta** [oegedijk/explainerdashboard#79]
Hi @oegedijk, is me, again. Is there some way to replace a metric showing in table Model Performance Metric? e.g., replace accuracy with balanced accuracy. I ask this because for rare events balanced accuracy is much more recomendable. I d'ont find this in documentation.

![image](https://user-images.githubusercontent.com/67707385/106832754-079d0280-6671-11eb-8044-90d1703f41e4.png)

**Comment by oegedijk** [comment]
Hi @mvpalheta the dashboard gets the metrics from `explainer.metrics()`, which returns a dict. So you can monkeypatch the method and insert your own metrics:

```python
def metrics2(self, cutoff=0.5, pos_label=None):
    return {'foo': 0.1}

ClassifierExplainer.metrics = metrics2
ExplainerDashboard(explainer).run()

```

Original method here: https://github.com/oegedijk/explainerdashboard/blob/28959485f7c41b078d8ca7443b9bf377f164282c/explainerdashboard/explainers.py#L2055

**Comment by mvpalheta** [comment]
hello @oegedijk ,
Ok, that's works fine. Thanks. I will close the issue
