### ISSUE TITLE
SHAPError with Explainer

### ISSUE THREAD

**Issue by naresh-sundarrajan** [oegedijk/explainerdashboard#8]
Hi! 

When trying to replicate the example dashboard, I get the following error: 

Here is the code: 

```
from explainerdashboard.explainers import ClassifierExplainer
from explainerdashboard.dashboards import ExplainerDashboard

from explainerdashboard.datasets import titanic_survive, titanic_names

X_train, y_train, X_test, y_test = titanic_survive()
train_names, test_names = titanic_names()

model = RandomForestClassifier(n_estimators=50, max_depth=5)
model.fit(X_train, y_train)

explainer = ClassifierExplainer(
                model, X_test, y_test,
                # optional:
                cats=['Sex', 'Deck', 'Embarked'],
                labels=['Not survived', 'Survived'])

ExplainerDashboard(explainer).run()

```
SHAPError: Additivity check failed in TreeExplainer! Please ensure the data matrix you passed to the explainer is the same shape that the model was trained on. If your data shape is correct then please report this on GitHub. Consider retrying with the feature_perturbation='interventional' option. This check failed because for one of the samples the sum of the SHAP values was 0.898516, while the model output was -3111090361071495795172390141309047352589574977119107048305877198218705179454949444899246221946253350348130845905799474606115208759423898693485753827793299777443235521296469068241830714822432908526887716104261809192590482006041690112.000000. If this difference is acceptable you can set check_additivity=False to disable this check.

**Comment by oegedijk** [comment]
Hi Naresh,

That seems to be an somewhat regular but stochastic bug with the previous version of the `shap` library. Could you try updating the shap library and see if the error persists?

Cheers

**Comment by oegedijk** [comment]
I will add a shap>=0.36 dependency to prevent this in the future

**Comment by naresh-sundarrajan** [comment]
> Hi Naresh,
> 
> That seems to be an somewhat regular but stochastic bug with the previous version of the `shap` library. Could you try updating the shap library and see if the error persists?
> 
> Cheers

I have updated this, still no luck!

**Comment by naresh-sundarrajan** [comment]
> I will add a shap>=0.36 dependency to prevent this in the future
Also, the docs explain the following way of importing: 

`from explainerdashboard import ClassifierExplainer, ExplainerDashboard`

This did not work for me, I had used this: 
```
from explainerdashboard.explainers import ClassifierExplainer
from explainerdashboard.dashboards import ExplainerDashboard
```

Is this appropriate?

**Comment by oegedijk** [comment]
Ah, that should work with the latest version, have you tried updating the library `pip install -U explainerdashboard` ?

(also just published the shap 0.36 requirement to pypi so latest version should be 0.2.8.1)

**Comment by oegedijk** [comment]
Did you try if you get the same error with pure shap code?

```python
shap_explainer = shap.TreeExplainer(model)
shap_values = shap_explainer.shap_values(X_test)
```

**Comment by naresh-sundarrajan** [comment]
@oegedijk Turns out it was a Shap issue. I updated from 0.36.0 to 0.37.0 using: 

`pip install git+https://github.com/slundberg/shap.git`

It works fine now! Thank you for your suggestions.
