### ISSUE TITLE
hide metrics table Model Performance Metric

### ISSUE THREAD

**Issue by mvpalheta** [oegedijk/explainerdashboard#80]
Hi @oegedijk,
Is there some way to hide some metrics in model summary, table Model Performance Metric? I read the documentation but not find this functionality. In source code the metrics are get by class ClassifierModelSummaryComponent, but that class d'ont have any parameter to hide. E.g., using the parameter hide_prauc only hide the PR AUC plot not the metric pr_auc_score. Below snapshot of the table

![image](https://user-images.githubusercontent.com/67707385/106834168-a9bdea00-6673-11eb-80c5-d89cf448699a.png)

**Comment by oegedijk** [comment]
Hi @mvpalheta,

Could perhaps instead add a paremeter `use_metrics` instead which would take a list of metrics (could even allow custom functions)? That seems more flexible than taking a lot of `hide_metricname` parameters.

**Comment by mvpalheta** [comment]
oh yes, that's more intelligent and elegant

**Comment by oegedijk** [comment]
So pushed the solution to the dev branch: https://github.com/oegedijk/explainerdashboard/tree/dev

new parameter `show_metrics` that also takes custom functions (that even get saved to and reloaded from yaml!)

**Comment by oegedijk** [comment]
Maybe you can give it a try and let me know if it works for you

**Comment by mvpalheta** [comment]
hello @oegedijk 
yes, a have tested and its works for me. But, i'm confused how to create custom function in this case, maybe an example in documentation can help. Thanks

**Comment by oegedijk** [comment]
yeah, will have to add more documentation when this gets formally released. You have to define a function that takes in `y_true` and `y_pred` and returns some number, e.g.:

```python
def mean_difference(y_true, y_pred):
  return np.mean(y_true)-np.mean(y_pred)

ExplainerDashboard(explainer, show_metrics=['accuracy', mean_difference])
```

For `ClassifierExplainer` I pass `y_true=np.where(y==pos_label,1,0)` and `y_pred=np.where(pred_proba>cutoff, 1, 0)` to the custom metric function. But maybe could think of a more flexible solution...

**Comment by mvpalheta** [comment]
Ok @oegedijk, Thanks a lot :-)

**Comment by oegedijk** [comment]
Now released: https://github.com/oegedijk/explainerdashboard/releases/tag/v0.3.2
