### ISSUE TITLE
Random uuid generated when selecting tabs with code

### ISSUE THREAD

**Issue by carlryn** [oegedijk/explainerdashboard#83]
Hej,

Because I've built some custom components, I've started to declare what tabs I want to use in code. However, this causes issues with uuids now being generated as name. I've stepped through the code and it seems that name is not being passed into the constructor of the components => shortuuid is being randomed.

In the following line no name attribute is being passed forward.
https://github.com/oegedijk/explainerdashboard/blob/d515b3c71e166ae0d8ef095435d4bdb91fd57fee/explainerdashboard/dashboard_tabs.py#L85-L86

Using version 0.3.1

Example code with explainer generated from the titanic dataset example:
```
from explainerdashboard import *
from flask import Flask
from explainerdashboard.custom import (
    IndividualPredictionsComposite,
    ModelSummaryTab
)

explainer = ClassifierExplainer.from_file('./explainer.joblib')
tabs = [ModelSummaryTab, IndividualPredictionsComposite]
db1 = ExplainerDashboard(explainer, tabs=tabs)
print(db1.app.callback_map.values())

app = db1.flask_server()

if __name__ == "__main__":
    app.run(host='localhost', debug=True)
```

The output from `print(db1.app.callback_map.values())` shows ids with uuid

**Comment by carlryn** [comment]
Creating a custom component of components and sending in a value for name solves the issue, but should of course be default :P

**Comment by carlryn** [comment]
Might just be the ModelSummaryTab that is the issue

**Comment by oegedijk** [comment]
Ah, yes, don't use the `*Tab` components, they are only there for backward compatibility, and they don't automatically set a name for their subcomponents. They have been deprecated in favor of the `*Composite` components. Should probably add it to them as well, just in case, or add a warning to the Tab components... 

But just use the `ClassifierModelStatsComposite` in this case...

**Comment by oegedijk** [comment]
Added a `DeprecationWarning` to the `*Tab` components for the next release...

**Comment by carlryn** [comment]
So if I understand correctly the tabs in:
https://github.com/oegedijk/explainerdashboard/blob/d515b3c71e166ae0d8ef095435d4bdb91fd57fee/explainerdashboard/dashboards.py#L248-L279

should be a list of *Composites?

**Comment by oegedijk** [comment]
sure, but the `*Composite` classes are all derived from the `ExplainerComponent` class. 

So you can pass anything to the `tabs` list as long as it is an `ExplainerComponent` object.

**Comment by oegedijk** [comment]
Now releases: https://github.com/oegedijk/explainerdashboard/releases/tag/v0.3.2
