### ISSUE TITLE
Shap additivity check

### ISSUE THREAD

**Issue by carlryn** [oegedijk/explainerdashboard#84]
Hej,

Having random additivity check exceptions thrown from shap when running the explainerdashboard, and even though I have been debugging them thoroughly they do not make sense. I've set up try catch clauses and saved `X_row` in `self.shap_explainer.shap_values(X_row)`, and still not able to reproduce the issue.

Due to this I'm looking into disabling the additivity check which is a keyword when computing shap values. See:
https://github.com/slundberg/shap/blob/f9bcf8a9610dcd0716dde8270f1266c2a24bd394/shap/explainers/_tree.py#L279

What would you think about adding check_additivity as an argument for the constructor of the explainerdashboard components, and then passing it when calculating shap_values?

**Comment by oegedijk** [comment]
Thought about adding `check_additivity=False` around `shap==0.35`, when it would throw a lot of these random additivity exceptions. (at some point had a `while` loop set up to keep trying until it randomly worked :). For me this hasn't been an issue with `shap>=0.36` though...

But so does it also throw the exceptions when you try

```
explainer.shap_explainer.shap_values(explainer.get_X_row(0))
```

or

```
explainer.shap_explainer.shap_values(explainer.X.iloc[[0]])
```

or 

```
explainer.shap_explainer.shap_values(X_test.iloc[[0]])
```

Could be that the `explainer` formats the data in a way that confuses the `shap_explainer` (especially now with with the memory saving measures in place that sets columns as `pd.category`, etc. )

**Comment by carlryn** [comment]
Will the exception have any effects on the updates of components?

I'm setting out my debug points in my try catch and computing the shap value without any exception thrown.
The sum of the shap value I receive when recalculating the shap value is the absolute value of what the exception is reporting.

> Additivity check failed in TreeExplainer! Please ensure the data matrix you passed to the explainer is the same shape that the model was trained on. If your data shape is correct then please report this on GitHub. Consider retrying with the feature_perturbation='interventional' option. This check failed because for one of the samples the sum of the SHAP values was -4.207260, while the model output was -0.657771. If this difference is acceptable you can set check_additivity=False to disable this check.

The sum of the SHAP values change every time it runs for the same row. E.g some runs -4.2 and next time -4.0. Model output is determenistic

**Comment by carlryn** [comment]
Running shap 0.37.0

**Comment by carlryn** [comment]
Seems that some components do get affected. Monkeypatched by replacing explainer._shap_explainer with an explainer inherited from TreeExplainer. 

`import shap
import collections

class CustomShapExplainer(shap.TreeExplainer):

    logged_X_errors = collections.deque(maxlen=5)
    logged_shap_values = collections.deque(maxlen=5)

    def shap_values(self, X):

        try:
            shap_values = super().shap_values(X, check_additivity=True)
            print("Calculated some shappies")
        except Exception as e:
            shap_values = super().shap_values(X, check_additivity=False)
            self.logged_X_errors.append(X)
            self.logged_shap_values.append(shap_values)
            print(e)

        return shap_values
`

**Comment by oegedijk** [comment]
Do you know where it throws the exception from in the dashboard? In the individual predictions tab or the whatif tab? 

I think this is just a warning, so the components should still work I guess but when it this far off `-4.207260, while the model output was -0.657771` then the output is basically nonsensical. (still better than the ones I used to get it would something like `1241234513241432.43, while the model output was -0.657771` :)

Anyway, do I understand you correctly that shap doesn't throw the error in the three ways of calculating them above, but does throw them in the dashboard? 

Could you try if there is a difference between these two:

```python
explainer.plot_contributions(index=0)
```

and

```python
explainer.plot_contributions(X_row=explainer.get_X_row(0))
```

**Comment by oegedijk** [comment]
Or try this:

```python
explainer.plot_contributions(
  X_row=explainer.get_row_from_input(
    explainer.get_X_row(0, merge=True)[explainer.columns_ranked_by_shap()].values[0].tolist(), 
    ranked_by_shap=True)
)
```

(this mimics the processing in the whatif tab)

**Comment by carlryn** [comment]
On the individual predictions tab I don't get any errors when updating individual plots, but when I am updating all at once through the select index component the error is thrown. It's thrown twice, so I guess that means the shap values are computed twice here. Looking at individual indexes I can see that the contribution plot is not correct when using the select index component, it is quite far of( this is also when shap throws error ). I've also used jupyter notebook for validation.

I think there is a tricky bug here somewhere. I don't know how dash is updating but I would assume some form of multiprocessing is used. 

All of the options you mention yield the same plot for me in jupyter notebook.

**Comment by oegedijk** [comment]
Ah, interesting! So this happens with this specific dataset and not with e.g. the Titanic dataset? The index selector callback literally just copies the index to the component index selector, so there should be no difference whether you set it directly from the component or with the index selector. (the reason you see the error twice, is that both the graph component and the table component independently calculate the shaps: bit of a waste but a trade-off to keep things modular)

My guess is that there must be some specific thing with the indexes that causes this? Are the indexes maybe all numbers? Encoded in some weird encoding? (could be that `dash` turns it into an `int` instead of a `str` behind the scenes. Maybe also cutting off leading `0`'s if there are any?).

I just added a patch that casts the `index` to `str` in the `dev` branch: https://github.com/oegedijk/explainerdashboard/tree/dev

Could you see if that helps?

**Comment by carlryn** [comment]
Interesting is that when running in debug mode with debug pointers the error doesn't happen :D Sometimes when running it is only one that throws error.

**Comment by carlryn** [comment]
It seems to me that things are pointing to shap and that something is not threadsafe. Found one assignment in shap when calculating shap values that assigns with self.

I've saved rows when it fails, and rows for every index are identical when entering the shap calculation.

**Comment by carlryn** [comment]
Alright, finally I have a conclusion.

Shap is not threadsafe!
When calculating shap values with the explainerdashboard I created deep copies of the computed shap explainer.
Then added flags to each composite so I knew which one was to calculate the shap values. Each composite then calculates the shap values with different explainers/objects.

Now I don't have any errors

**Comment by oegedijk** [comment]
Ah, wow, that is a tricky bug to figure out! Thanks!

Could you elaborate the fix? Should every component make a (deep)copy of the explainer? And why do you think you get this bug here but not with other datasets? Depends on the shap calculation time?

**Comment by oegedijk** [comment]
Also: any ideas on how to make `shap` threadsafe?

**Comment by carlryn** [comment]
Every component that potentially will calculate shap values at the same time as some other component will need to create copies(probably deep). I was focusing on the IndividualPredictionsComposite with two components calculating shap values. I made this fix quick for this specific use-case.

First when calculating the shap values I made  deep copies for the two composites.
https://github.com/oegedijk/explainerdashboard/blob/d515b3c71e166ae0d8ef095435d4bdb91fd57fee/explainerdashboard/explainers.py#L1825-L1830
Potentially it could be better design to make the copies in the constructor of the components that will calculate shap values in their callbacks. Then you don't need to know how the dashboard should look when creating the explainer.

In our case the shap values are computed in
https://github.com/oegedijk/explainerdashboard/blob/d515b3c71e166ae0d8ef095435d4bdb91fd57fee/explainerdashboard/explainers.py#L1029-L1030
and more exactly at 
https://github.com/oegedijk/explainerdashboard/blob/d515b3c71e166ae0d8ef095435d4bdb91fd57fee/explainerdashboard/explainers.py#L1073

In `def get_contrib_df(...)`  then just add a flag to know which component that is calculating the shap values  `def get_contrib_df(..., component_flag=False)` and select shap explainer to compute shap values depending on the value of the flag.
And as well here, sending in a complete shap_explainer object might be the better idea instead because then you don't need to keep track of a mapping between component names/flags and the shap explainers.

Issues caused by threadsafety are tricky to catch. They can be dependent on the machine and in this case dataset/model. Maybe some of our computation are heavier, or lighter at some specific point which then makes them alter the same object at the same time.

When going through the shap code for generating the shap values I saw they assigned a variable with `self` in the method. If this object becomes modified at the same time by two processes referencing the same object then this issue can happen. The way to fix it would then be to remove the self assignment so it becomes a local variable to the method :)

**Comment by oegedijk** [comment]
Yeah, I think adding a parameter  `shap_explainer=None` to `plot_dependence()` and `get_contrib_df()` would probably be the most straightforward. 

Then the component could make a deepcopy of `explainer.shap_explainer`, and pass it along. The whole point of the modular design was that each component could make use of the same explainer object though! So will have to break that principle in this case. Anyway, a foolish consistency is the hobgoblin of small minds and all that :)

**Comment by oegedijk** [comment]
might be worth submitting a PR to `shap` to make it threadsafe though if that variable can be saved in the local namespace...

**Comment by oegedijk** [comment]
This should be mostly fixed in latest release as long you do not load from external sources: if the index exists in `X_test` then simply do a lookup instead of recalculating the shap values. 

https://github.com/oegedijk/explainerdashboard/releases/tag/v0.3.2.2

**Comment by oegedijk** [comment]
Now figured out the proper solution: just add some locks to prevent the race condition. Will be in next release!
