### ISSUE TITLE
Debug mode in part of Flask app

### ISSUE THREAD

**Issue by oleg-savko** [oegedijk/explainerdashboard#86]
If I use explainerdashboard as part of flask app like in docs:

```python
db = ExplainerDashboard(explainer, server=app, url_base_pathname="/dashboard/")

@app.route('/dashboard')
def return_dashboard():
    return db.app.index()

```

Its add dynamic routes, and if enable debug mode, then got following errors:

_AssertionError: A setup function was called after the first request was handled.  This usually indicates a bug in the application where a module was not imported and decorators or other functionality was called too late.
To fix this make sure to import all your view modules, database models and everything related at a central place before the application starts serving requests._

I understand that its more related to flask, but can you suggest how handle this situation?

**Comment by oegedijk** [comment]
Did you iniate the flask app correctly? i.e.

```python
from flask import Flask

app = Flask(__name__)
```

Although I think you could also get away with leaving out

```python
@app.route('/dashboard')
def return_dashboard():
    return db.app.index()
```
altogether...

**Comment by oegedijk** [comment]
Did you figure this one out? Otherwise I'll close the issue...
