### ISSUE TITLE
Add ability to load prediction individual predictions by any specify id (not by list of id)

### ISSUE THREAD

**Issue by oleg-savko** [oegedijk/explainerdashboard#89]
Currently we can specify `set_X_row_func,  set_y_func, set_index_list_func`, so its seems like no problem to load features/labels for any specify id, but we can select only id from available dropdawn list from UI.

Its would be very useful, if we can to avoid this restriction and load Individual Restriction for any specified index.

**Comment by oegedijk** [comment]
Hi Oleg,

I'm not sure I understand your question? The `index_list_func` is used to populate the dropdowns, and the `X_row_func` is used to retrieve the row of input features. 

So would you like to have an index selector that is just a free text field in which you can input any index instead of a dropdown with all available indexes? I suppose this should be possible...

**Comment by oleg-savko** [comment]
Yes, exactly! Its add great possibility to explain decision for records which insert in database after build dashboard and in real-time!!! What should be very useful)  
Functions` set_X_row_func, set_y_func` seems like add big power, but `index_list_func` restrict it.. and even load a lot of index of records in dropdowns (еx >100_000, 1_000_000, 10_000_000..) seems like very bad idea, make page huge and not responsive.

Very wait for add possibility to skip this restriction and get power of functions `set_X_row_func, set_y_func` completely!

**Comment by hkoppen** [comment]
Isn't that already possible? `RegressionRandomIndexComponent` allows to type in an index after deleting the default chosen one (hit the small cross next to the number or Del). It is featuring a smart search, i.e. typing '123' leads to a filtered dropdown menu showing stuff like 1234, 1235, 2123, ... only.

**Comment by oleg-savko** [comment]
> Isn't that already possible? `RegressionRandomIndexComponent` allows to type in an index after deleting the default chosen one (hit the small cross next to the number or Del). It is featuring a smart search, i.e. typing '123' leads to a filtered dropdown menu showing stuff like 1234, 1235, 2123, ... only.

You can type, but when you type index which not in index list, you got _No results found_ and you cant select it to load features/label from db now.

**Comment by oegedijk** [comment]
Hi Oleg, I'm currently working on the implementation for this (you can check out the `dev` branch and pass `index_dropdown=False` to see how it works. Currently I am still checking the input against the possible values of index in `get_index_list()`. (in order not to generate too many stacktraces, and give feedback inside the dashboard when a non-existent index has been entered).

But if I understand you're usecase correctly you would like to be able to disable this check as well?

**Comment by oegedijk** [comment]
added a parameter `index_check=False` to not check for index existing when propagating to other component.

Released with 0.3.2: https://github.com/oegedijk/explainerdashboard/releases/tag/v0.3.2

**Comment by oleg-savko** [comment]
> Hi Oleg, I'm currently working on the implementation for this (you can check out the `dev` branch and pass `index_dropdown=False` to see how it works. Currently I am still checking the input against the possible values of index in `get_index_list()`. (in order not to generate too many stacktraces, and give feedback inside the dashboard when a non-existent index has been entered).
> 
> But if I understand your usecase correctly you would like to be able to disable this check as well?

Hi @oegedijk great work! I tried to use your new version :)
But unfortunately, I still can`t to load to load features by any index, maybe I something missed, but now I have a problem in this snippet of code:

```
if index in self.idxs:
    X_row = self.X.iloc[[self.get_idx(index)]]
elif isinstance(index, int) and index >= 0 and index < len(self):
    X_row = self.X.iloc[[index]]
elif self._get_X_row_func is not None and index in self.get_index_list():
    X_row = self._get_X_row_func(index)
else:
    raise IndexNotFoundError(index=index)
```

`elif self._get_X_row_func is not None and index in self.get_index_list()`
I have specified function `self._get_X_row_func` but it cant load it because, it not in  `self.get_index_list()`, and so I have the same problem :(


Tell me please, if I misleading and can load features by any index and avoid this restriction `elif self._get_X_row_func is not None and index in self.get_index_list()` 

----------------------

I saw in release notes, that you introduce new function `explainer.index_exists(index)`, may be it can help to make check index more robust for this part of code) 
For example if we can specify a function to it (like `self._get_X_row_func, self._get_y_row_func`), and add it to check index before load features.

**Comment by oegedijk** [comment]
You are right, I still check against the list provided by `explainer.get_index_list()` (which can be set with `explainer.set_index_list_func(funct)`. Which I guess doesn't work with your usecase. 

Let me have a look how I can disable all those checks, and allow any index to be passed on to the get_X_row_func. 

(by default I would like to keep this check in, to keep things clean and prevent sql injection attacks for example. But if you know what you're doing you should be allowed to override it.)

**Comment by oleg-savko** [comment]
> You are right, I still check against the list provided by `explainer.get_index_list()` (which can be set with `explainer.set_index_list_func(funct)`. Which I guess doesn't work with your usecase.
> 
> Let me have a look how I can disable all those checks, and allow any index to be passed on to the get_X_row_func.
> 
> (by default I would like to keep this check in, to keep things clean and prevent sql injection attacks for example. But if you know what you're doing you should be allowed to override it.)

Yes, it will be great!)
What do you think about ability to providing custom method for checking index as I mentioned here?

> I saw in release notes, that you introduce new function explainer.index_exists(index), may be it can help to make check index more robust for this part of code)
> For example if we can specify a function to it (like self._get_X_row_func, self._get_y_row_func), and add it to check index before load features.

With this ability, we can implement business logic to protect yourself (for example, check if corresponding index exists in database and so on..) and get beautiful green/red highlights which already you prepared for us.

**Comment by oegedijk** [comment]
> What do you think about ability to providing custom method for checking index as I mentioned here?

Yeah, I had that in there at some point (you can still see the reference in the release notes), but then I figured I could do without it, but now it seems that was a mistake 🤷  :)

Will add it back in!

**Comment by oegedijk** [comment]
Just pushed a version to the dev branch where I think I've got it working. Could you check it out and let me know if it works for you?

This at least seems to work:

```python

X_train, y_train, X_test, y_test = titanic_survive()
model = RandomForestClassifier(n_estimators=50, max_depth=4).fit(X_train, y_train)

X_test1, y_test1 = X_test.iloc[:100], y_test.iloc[:100]
X_test2, y_test2 = X_test.iloc[100:], y_test.iloc[100:]

explainer = ClassifierExplainer(model, X_test1, y_test1)     

print("Test names:\n")
print(X_test1.index[0]) # this one is in explainer.idxs
print(X_test2.index[0]) # this one is in index_list 
print(X_test2.index[-1], "\n\n") # this one isn't

def index_exists_func(index):
    return index in X_test2.index

def index_list_func():
    # only returns first 50 indexes
    return list(X_test2.index[:50])

def y_func(index):
    idx = X_test2.index.get_loc(index)
    return y_test2.iloc[[idx]]

def X_func(index):
    idx = X_test2.index.get_loc(index)
    return X_test2.iloc[[idx]]

explainer.set_index_exists_func(index_exists_func)
explainer.set_index_list_func(index_list_func)
explainer.set_X_row_func(X_func)
explainer.set_y_func(y_func)

ExplainerDashboard(explainer, index_dropdown=False).run()
```

**Comment by oegedijk** [comment]
https://github.com/oegedijk/explainerdashboard/tree/dev

**Comment by oleg-savko** [comment]
> Just pushed a version to the dev branch where I think I've got it working. Could you check it out and let me know if it works for you?

Thanks a lot @oegedijk! I will try to test it now :)
Seems now it work fine with this case!
In my first test, I was found only one bug currently:

 ```
 File "/Users/alehsauko/miniconda/envs/ru_score/lib/python3.8/site-packages/explainerdashboard/explainers.py", line 2717, in plot_prediction_result
    preds_df = self.prediction_result_df(index, X_row)
  File "/Users/alehsauko/miniconda/envs/ru_score/lib/python3.8/site-packages/explainerdashboard/explainers.py", line 2388, in prediction_result_df
    int_idx = self.get_idx(index)
  File "/Users/alehsauko/miniconda/envs/ru_score/lib/python3.8/site-packages/explainerdashboard/explainers.py", line 384, in get_idx
    raise IndexNotFoundError(index=index)
explainerdashboard.explainer_methods.IndexNotFoundError: Index 11667144 not found!
```
`prediction_result_df` seems not work for index which not in index_list, I think it can be simple fixed, just add the same logic, check index, load features and call `self.model.predict_proba(..)` if it not in index_list))

I will let you know, if I found something more)

**Comment by oegedijk** [comment]
Think this should now be fixed?

**Comment by oleg-savko** [comment]
> Think this should now be fixed?
Now I try to test update version from dev branch.  
The `prediction_result_df` seems start work correct!!! (maybe it will be good to just add loaded banner like on all other charts).

Now seems start to not working plots with shap values :( 
Following exception thrown:

> File "/Users/alehsauko/miniconda/envs/ru_score/lib/python3.8/site-packages/explainerdashboard/dashboard_components/shap_components.py", line 1088, in update_output_div
>     plot = self.explainer.plot_contributions(str(index), topx=depth,
>   File "/Users/alehsauko/miniconda/envs/ru_score/lib/python3.8/site-packages/explainerdashboard/explainers.py", line 49, in inner
>     return func(self, *args, **kwargs)
>   File "/Users/alehsauko/miniconda/envs/ru_score/lib/python3.8/site-packages/explainerdashboard/explainers.py", line 1424, in plot_contributions
>     contrib_df = self.get_contrib_df(index, X_row, topx, cutoff, sort, pos_label)
>   File "/Users/alehsauko/miniconda/envs/ru_score/lib/python3.8/site-packages/explainerdashboard/explainers.py", line 62, in inner
>     return func(self, **kwargs)
>   File "/Users/alehsauko/miniconda/envs/ru_score/lib/python3.8/site-packages/explainerdashboard/explainers.py", line 1151, in get_contrib_df
>     shap_values = self.get_shap_row(index, pos_label=pos_label)
>   File "/Users/alehsauko/miniconda/envs/ru_score/lib/python3.8/site-packages/explainerdashboard/explainers.py", line 49, in inner
>     return func(self, *args, **kwargs)
>   File "/Users/alehsauko/miniconda/envs/ru_score/lib/python3.8/site-packages/explainerdashboard/explainers.py", line 2116, in get_shap_row
>     shap_row = pd.DataFrame(self.shap_explainer.shap_values(X_row)[pos_label], columns=self.columns)
> IndexError: index 1 is out of bounds for axis 0 with size 1

Not exactly know what `pos_label` here, but as expected `self.shap_explainer.shap_values(X_row)` return just one records, end so index out of bound exception occurs (
Mb here should be just `self.shap_explainer.shap_values(X_row)[0]` ?

**Comment by oegedijk** [comment]
Yeah, you got caught in some in-process refactoring on the `dev` branch :)

Added a method get_shap_row() to retrieve one row of shap values for a particular index, but the `shap` library returns has different return formats for different classifier models, so all that had not been incorporated yet. Should work now!

**Comment by oleg-savko** [comment]
> Yeah, you got caught in some in-process refactoring on the `dev` branch :)
> 
> Added a method get_shap_row() to retrieve one row of shap values for a particular index, but the `shap` library returns has different return formats for different classifier models, so all that had not been incorporated yet. Should work now!

Yes, seems like now from dev branch it work fine! :)

**Comment by oegedijk** [comment]
Released! https://github.com/oegedijk/explainerdashboard/releases/tag/v0.3.2.2

**Comment by oegedijk** [comment]
Hi @oleg-savko, given that you now have some experience with using the external loading functions, would you perhaps have some time to construct a small toy example with e.g. a sqlite database and redis caching that we could add to the documentation?
