### ISSUE TITLE
add to conda-forge?

### ISSUE THREAD

**Issue by raybellwaves** [oegedijk/explainerdashboard#9]
I'll be happy to do so if it isn't on conda-forge yet

**Comment by raybellwaves** [comment]
https://github.com/conda-forge/staged-recipes/pull/13190

**Comment by oegedijk** [comment]
Ah, good point! I can try to get in on there later this week. Would be good to intergrate it with the pypi release that happens through a github action whenever I make a new release on github.

**Comment by raybellwaves** [comment]
> Would be good to intergrate it with the pypi release that happens through a github action whenever I make a new release on github.

conda-forge has bots then when you do a release it will update the version.

**Comment by oegedijk** [comment]
Ah, wonderful! 

But it seems that the dtreeviz and dash-auth requirements might be an issue?

**Comment by raybellwaves** [comment]
> dtreeviz and dash-auth requirements might be an issue?

Yes. May Have to wait a bit for those to be resolved.
