### ISSUE TITLE
Shap Dependence toggle outlier treatment

### ISSUE THREAD

**Issue by oleg-savko** [oegedijk/explainerdashboard#93]
Problem: sometimes its very useful to see on shap values (Shap Dependence plot) with and without outliers. 
It will be very useful if there is a toggle switch button on plot which enable/disable outlier treatment.

Outliers often make a lot of mess on shap dependence plot, and if exist you often not can view correct colored interaction with dependent features. We of course can treat it before passing to explainer, but look on data without treatment also very useful, so has both options will be great!

What do you think about it @oegedijk ? 
Maybe if we can provide both dataset (with and without treatment) or just option to calculate shap values on both origin dataset and dataset with outlier treatment internally?

**Comment by oleg-savko** [comment]
I understand, that we always can zoom specific region on plot, but sometimes its not comfortable, and yes its useful to have a option to winsorize the shap dependence plot. 

And one more think that you cant fix with zoom specific region, is to see real colored (red/blue) correlation with interaction feature. Because if some outlier with very big/small values exist, all other features would be very small/big regarding this outlier. 

And so interaction feature axis became useless, if outlier exists :(

**Comment by oegedijk** [comment]
added winsors in dev, could you check if this is what you were looking for?

**Comment by oleg-savko** [comment]
> added winsors in dev, could you check if this is what you were looking for?

Hi @oegedijk ! 
I try to check dev branch, I look at `plot_dependence` and seems its work not correct:
1. You should treat outliers not in shap values, but in original feature.
Here a problem:
```
plot_idxs = self.get_idx_sample(plot_sample, highlight_index, 
self.get_shap_values_df(pos_label)[col].values, winsor)
```
Should be something like:
```
plot_idxs = self.get_idx_sample(plot_sample, highlight_index, 
            self.X[col], winsor)
```
2. Its not outlier treatment, if you just filter by percentile:
```
winsor_bounds = np.percentile(winsor_array, [winsor, 100-winsor])
idx_sample = idx_sample[(winsor_array > winsor_bounds[0]) 
                                        & (winsor_array < winsor_bounds[1])]
```
The simplest way for this purpose is use for example standard `IQR`(not parameterized) or `Z-score`(can be parameterized by sigma). 
They are very easy to implement, you can check some info here for example:
https://medium.com/analytics-vidhya/outlier-treatment-9bbe87384d02

**Comment by oegedijk** [comment]
You could also exclude outlier from the color_col feature, which is perhaps more what you are looking for?

**Comment by oleg-savko** [comment]
> You could also exclude outlier from the color_col feature, which is perhaps more what you are looking for?

Yes, seems you right, its need to remove outlier by `feature x-axis`, and by `color_col feature interaction-axis`. 
By shap value axis its not need, I think they cant have outliers and in current implementation just remove data which is not look like outlier (in features terms of view). 

> Winsorizing is the simplest form of outlier treatment, but IQR could be even simpler in the UX in the sense that it would be just a switch or toggle. Hmm, let me have a look at what makes sense...

I think it will be useful to have several option how to treat outliers:
1. `IQR` good option when you dont want to customize any parameters
2. Using `Z-score` you can choose via `sigma` to be more conservative or not.
3. Maybe sometimes `Winsorizing` also can be good option.

**Comment by oegedijk** [comment]
Don't want to have too many toggles though. How about a dropdown with label "remove outlier", and then select [None, shap, col, color_color], and then it simply removes 1.5* IQR from that axis?

**Comment by oleg-savko** [comment]
> Don't want to have too many toggles though. How about a dropdown with label "remove outlier", and then select [None, shap, col, color_color], and then it simply removes 1.5* IQR from that axis?

I think its doesnt really need that option `[None, shap, col, color_color]`, "remove outlier" its mean removing it from features and so removing it from `[col, color_col]` corresponding and just one toggle. 
But maybe I`m wrong, and it will be useful for someone.

About algorithm, what do you think about passing argument with how treat outlier in `ClassifierExplainer/ExplainerDashboard`, when you build it? In that case user can select what he want.
But for first iteration `IQR` would be enough)

**Comment by oegedijk** [comment]
Added this to the latest release: https://github.com/oegedijk/explainerdashboard/releases/tag/v0.3.3

**Comment by oleg-savko** [comment]
> Added this to the latest release: https://github.com/oegedijk/explainerdashboard/releases/tag/v0.3.3

Hi @oegedijk, great job, glad to hear it)

I just try to test you new version, and found one bug now, you use: 
`q1, q3 = np.percentile(outlier_array1[idx_sample], [25, 75])`  

but if data has a `nan` value then result would be `nan, nan` and remove all data ((

and also mb need to check that `outlier_array2[idx_sample]` not empty, because in that case second invocation `q1, q3 = np.percentile(outlier_array2[idx_sample], [25, 75])`  throw error:

> ValueError: zero-size array to reduction operation minimum which has no identity

Solution  just to use here: `q1, q3 = np.nanpercentile(outlier_array2[idx_sample], [25, 75])`

**Comment by oegedijk** [comment]
cool, thanks for the catch!

**Comment by oleg-savko** [comment]
> cool, thanks for the catch!

Hi @oegedijk ! 
Can you please approximate tell, when to expect fix for this bug?

**Comment by oegedijk** [comment]
Was going to wait till I had time to do some other fixes, but didn't find any, so just did a quick release with just this fix: https://github.com/oegedijk/explainerdashboard/releases/tag/v0.3.3.1

**Comment by oleg-savko** [comment]
> Was going to wait till I had time to do some other fixes, but didn't find any, so just did a quick release with just this fix: https://github.com/oegedijk/explainerdashboard/releases/tag/v0.3.3.1

Great thanks you very much!)
