### ISSUE TITLE
Does expainerdashboard work with SDGClassifier and MLPClassifier?

### ISSUE THREAD

**Issue by apavlo89** [oegedijk/explainerdashboard#96]
I get error ValueError: Parameter shap='gues'', but failed to to guess the type of shap explainer to use. Please explicitly pass a `shap` parameter to the explainer, e.g. shap='tree', shap='linear', etc.

**Comment by oegedijk** [comment]
Hi, @apavlo89, the explainer tries to guess which shap explainer to use (shap.TreeExplainer, shap.LinearExplainer, shap.TreeExplainer), etc, based on the name of the model. Currently it does not autodetect SDHClassifier and MLPClassifier, which is why you got that error message.

For the SGDClassifier you could try passing `shap='linear'` and for the MLPClassifier `shap='kernel'`. 

Will see if I can clear up that error message, and also probably default to `shap='kernel'` since shap.KernelExplainer is model agnostic and should work for any model.

**Comment by oegedijk** [comment]
So this seems to work except that SGDClassifier calculates pred_probas==0, which messes with calculating logodds, and so with the prediction summary:

```python
from explainerdashboard import *
from sklearn.linear_model import SGDClassifier
from explainerdashboard.datasets import *

X_train, y_train, X_test, y_test = titanic_survive()
model = SGDClassifier(loss='log').fit(X_train, y_train)
explainer = ClassifierExplainer(model, X_test, y_test, shap='linear')   
ExplainerDashboard(explainer, shap_interaction=False).run()
```

**Comment by oegedijk** [comment]
and this for MLPClassifier:

```python
from explainerdashboard import *
from sklearn.neural_network import MLPClassifier
from explainerdashboard.datasets import *

X_train, y_train, X_test, y_test = titanic_survive()
model = MLPClassifier().fit(X_train, y_train)
explainer = ClassifierExplainer(model, X_test, y_test, shap='kernel', cats=['Sex', 'Deck', 'Embarked'])   
ExplainerDashboard(explainer, shap_interaction=False).run()
```

**Comment by oegedijk** [comment]
Noticed that the whatif components don't work with slow shap calculations such as kernel shap as shap is apparently not thread safe. So in the whatif tab the shap values get calculated in parallel in separate threads for both the contribution graph and contribution table, causing a thread conflict and an error. 

Will see what can be done about this...

**Comment by oegedijk** [comment]
Managed to fix it: had to add some locks to prevent the multithreading race conditions with shap. Will be in next release!

**Comment by apavlo89** [comment]
Fantastic! I have to say your work on this is incredible and it is so so useful! Looking forward to seeing where this evolves!

**Comment by oegedijk** [comment]
You're welcome :)

**Comment by apavlo89** [comment]
> ```python
> model = SGDClassifier(loss='log').fit(X_train, y_train)
> ```

When I put the following hyperparameters:

`model = SGDClassifier(alpha=0.01, eta0=0.01, fit_intercept=False, l1_ratio=0.0, learning_rate="invscaling", loss="hinge", penalty="elasticnet", power_t=0.0).fit(X_train, y_train)`

I get:

`AssertionError: for ClassifierExplainer, model should be a scikit-learn compatible *classifier* model that has a predict_proba(...) method, so not a <class 'sklearn.linear_model._stochastic_gradient.SGDClassifier'>!`

Weird. Your example `model = SGDClassifier(loss='log').fit(X_train, y_train)` runs just fine. What do you make of this?
